[package]
name = "pallet-relayer-rpc"
version = "0.1.0"
authors = ["Orbinum Team"]
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
hex = "0.4"
jsonrpsee = { version = "0.24.9", features = ["server", "macros", "client"] }
pallet-relayer-runtime-api = { path = "../runtime-api" }
serde = { version = "1.0", features = ["derive"] }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2512" }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2512" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2512" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2512" }
