[package]
name = "pallet-relayer-rpc"
version = "0.1.0"
authors = ["Orbinum Team"]
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
hex = "0.4"
jsonrpsee = { version = "0.24.9", features = ["server", "macros", "client"] }
pallet-relayer-runtime-api = { path = "../runtime-api" }
serde = { version = "1.0", features = ["derive"] }
sp-api = { version = "40.0.0" }
sp-blockchain = { version = "43.0.0" }
sp-core = { version = "39.0.0" }
sp-runtime = { version = "45.0.0" }
