#!/usr/bin/env bash
# =============================================================================
# insert-session-keys.sh — Insert session keys (Aura + GRANDPA) into a
#                          running validator node's keystore.
#
# Usage:
#   ./insert-session-keys.sh --validator N [--container NAME]
#   ./insert-session-keys.sh --validator 1
#   ./insert-session-keys.sh --validator 1 --container orbinum-validator
#
# Requirements:
#   Keys must be in keys/validator-N/ as generated by generate-keys.sh.
#   The validator container must be running. Its RPC (9944) only listens on
#   127.0.0.1 inside the container, so the calls run via `docker exec`.
#   The container image must ship `curl` (the testnet image does).
#
# What it does:
#   Calls author_insertKey for "aura" and "gran" via JSON-RPC.
#   Keys are written to the node's local keystore (--base-path/keystore/).
#   The EVM relay address is derived automatically from the Aura mnemonic
#   at node startup — no separate evmr key insertion is needed.
#   After this, call author_rotateKeys and register on-chain via session.setKeys.
# =============================================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ── Parameters ────────────────────────────────────────────────────────────────
VALIDATOR=""
CONTAINER="orbinum-validator"
RPC_URL="http://localhost:9944"   # resolved INSIDE the container via docker exec

while [[ $# -gt 0 ]]; do
  case "$1" in
    --validator) VALIDATOR="$2"; shift 2 ;;
    --container) CONTAINER="$2"; shift 2 ;;
    *) echo -e "Usage: $0 --validator N [--container NAME]"; exit 1 ;;
  esac
done

if [[ -z "$VALIDATOR" ]]; then
  echo -e "${RED}Error: --validator is required${NC}"
  echo -e "Usage: $0 --validator 1 [--container orbinum-validator]"
  exit 1
fi

# All RPC calls run inside the validator container (RPC binds 127.0.0.1 only).
rpc_call() {
  docker exec -i "$CONTAINER" curl -sf -X POST "$RPC_URL" \
    -H "Content-Type: application/json" \
    -d "$1" 2>&1
}

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  echo -e "${RED}Error: container '$CONTAINER' is not running${NC}"
  echo -e "Start it first, or pass the right name with --container."
  exit 1
fi

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEYS_DIR="$SCRIPT_DIR/keys/validator-$VALIDATOR"

if [[ ! -d "$KEYS_DIR" ]]; then
  echo -e "${RED}Error: No keys found at $KEYS_DIR${NC}"
  echo -e "Generate them first with: ${CYAN}./generate-keys.sh${NC}"
  exit 1
fi

# ── Read keys ─────────────────────────────────────────────────────────────────
AURA_PHRASE=$(jq -r '.secretPhrase' "$KEYS_DIR/aura.json")
AURA_PUBKEY=$(jq -r '.publicKey'    "$KEYS_DIR/aura.json")

GRAN_PHRASE=$(jq -r '.secretPhrase' "$KEYS_DIR/grandpa.json")
GRAN_PUBKEY=$(jq -r '.publicKey'    "$KEYS_DIR/grandpa.json")

echo -e "${CYAN}${BOLD}Inserting session keys for Validator $VALIDATOR${NC}"
echo -e "  Container:      ${CONTAINER}"
echo -e "  RPC (internal): ${RPC_URL}"
echo -e "  Aura pubkey:    ${AURA_PUBKEY}"
echo -e "  GRANDPA pubkey: ${GRAN_PUBKEY}"
echo -e "  EVM relay:      (auto-derived from Aura mnemonic at node startup)"
echo ""

# ── Check node connectivity ───────────────────────────────────────────────────
echo -e "${YELLOW}Checking node connectivity...${NC}"
if ! rpc_call '{"id":1,"jsonrpc":"2.0","method":"system_health","params":[]}' \
  > /dev/null 2>&1; then
  echo -e "${RED}Error: Cannot reach the RPC inside '$CONTAINER'${NC}"
  echo -e "Make sure the node is running and the image ships curl."
  exit 1
fi
echo -e "${GREEN}✓ Node is reachable${NC}\n"

# ── Helper: insert a single key ───────────────────────────────────────────────
insert_key() {
  local key_type="$1"
  local phrase="$2"
  local pubkey="$3"
  local display="$4"

  echo -e "${YELLOW}Inserting ${display}...${NC}"
  RESPONSE=$(rpc_call "{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"author_insertKey\",\"params\":[\"${key_type}\",\"${phrase}\",\"${pubkey}\"]}")

  if echo "$RESPONSE" | jq -e '.result == null' > /dev/null 2>&1; then
    echo -e "${GREEN}  ✓ ${display} inserted${NC}"
    return 0
  elif echo "$RESPONSE" | jq -e '.error' > /dev/null 2>&1; then
    ERR=$(echo "$RESPONSE" | jq -r '.error.message // .error')
    echo -e "${RED}  ✗ Failed to insert ${display}: ${ERR}${NC}"
    return 1
  else
    # author_insertKey returns null on success
    echo -e "${GREEN}  ✓ ${display} inserted${NC}"
    return 0
  fi
}

# ── Insert keys ───────────────────────────────────────────────────────────────
insert_key "aura" "$AURA_PHRASE" "$AURA_PUBKEY" "Aura (Sr25519)"
insert_key "gran" "$GRAN_PHRASE" "$GRAN_PUBKEY" "GRANDPA (Ed25519)"

# ── Rotate keys (get combined session key) ────────────────────────────────────
echo ""
echo -e "${YELLOW}Calling author_rotateKeys to get the combined session key...${NC}"
ROTATE_RESPONSE=$(rpc_call '{"id":1,"jsonrpc":"2.0","method":"author_rotateKeys","params":[]}')

SESSION_KEY=$(echo "$ROTATE_RESPONSE" | jq -r '.result // empty')

if [[ -n "$SESSION_KEY" ]]; then
  echo -e "${GREEN}✓ Session key (register this on-chain):${NC}"
  echo -e "  ${BOLD}${SESSION_KEY}${NC}"
  echo ""
  echo "$SESSION_KEY" > "$KEYS_DIR/session_key.txt"
  chmod 600 "$KEYS_DIR/session_key.txt"
  echo -e "${GREEN}Saved to: $KEYS_DIR/session_key.txt${NC}"
else
  echo -e "${YELLOW}⚠ Could not retrieve session key automatically.${NC}"
  echo -e "  Call manually: ${CYAN}docker exec $CONTAINER curl -s $RPC_URL -H 'Content-Type: application/json' \\${NC}"
  echo -e "  ${CYAN}  -d '{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"author_rotateKeys\",\"params\":[]}'${NC}"
fi

# ── Next steps ────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}══════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}${BOLD} Registration flow — complete these steps IN ORDER        ${NC}"
echo -e "${CYAN}${BOLD}══════════════════════════════════════════════════════════${NC}"
echo ""

echo -e "${BOLD}Step 1 — Restart the node${NC}"
echo -e "  Restart the node so it loads the Aura key from its keystore."
echo -e "  At startup the node automatically derives your EVM relay address"
echo -e "  from the Aura mnemonic and submits register_relayer on-chain."
echo ""

echo -e "${BOLD}Step 2 — Register session keys on-chain${NC}"
echo -e "  Polkadot.js Apps → Developer → Extrinsics"
echo -e "  Pallet:  session"
echo -e "  Method:  setKeys(keys, proof)"
echo -e "  keys:    ${SESSION_KEY:-<session key from above>}"
echo -e "  proof:   0x"
echo -e "  Sign with: your validator account (needs small balance for tx fee)"
echo ""

echo -e "${BOLD}Step 3 — Submit validator registration${NC}"
echo -e "  Both session keys (Step 2) and EVM relayer (auto at Step 1) must be set."
echo -e "  Polkadot.js Apps → Developer → Extrinsics"
echo -e "  Pallet:  validatorSet"
echo -e "  Method:  registerValidator()"
echo -e "  Sign with: your validator account (needs small balance for tx fee)"
echo -e "  ${YELLOW}→ Your account enters the pending queue.${NC}"
echo ""

echo -e "${BOLD}Step 4 — Wait for sudo/governance approval${NC}"
echo -e "  A network operator must call:"
echo -e "  Pallet:  validatorSet"
echo -e "  Method:  approveValidator(who)"
echo -e "  ${YELLOW}→ Your node becomes an active validator at the next session rotation.${NC}"
echo ""
echo -e "${CYAN}${BOLD}══════════════════════════════════════════════════════════${NC}"
