[package]
name = "pallet-shielded-pool-runtime-api"
version = "0.1.0"
authors = ["Orbinum Team"]
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
pallet-shielded-pool = { path = "..", default-features = false }
parity-scale-codec = { version = "3.6", default-features = false, features = ["derive"] }
scale-info = { version = "2.11", default-features = false, features = ["derive"] }
sp-api = { version = "43.0.0", default-features = false }
sp-core = { version = "43.0.0", default-features = false }
sp-runtime = { version = "48.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"pallet-shielded-pool/std",
	"sp-api/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
]
