
//! Autogenerated weights for pallet_shielded_pool
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-01-19, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBook-Air-de-Nolasco.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/orbinum-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_shielded_pool
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=frame/shielded-pool/src/weights.rs
// --template=./scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_shielded_pool.
pub trait WeightInfo {
	fn shield() -> Weight;
	fn private_transfer() -> Weight;
	fn unshield() -> Weight;
	fn set_disclosure_verifying_key() -> Weight;
	fn set_audit_policy() -> Weight;
	fn request_disclosure() -> Weight;
	fn approve_disclosure() -> Weight;
	fn reject_disclosure() -> Weight;
	fn submit_disclosure() -> Weight;
	fn batch_submit_disclosure_proofs(n: u32) -> Weight;
	fn shield_batch(n: u32) -> Weight;
	fn register_asset() -> Weight;
	fn verify_asset() -> Weight;
	fn unverify_asset() -> Weight;
}

/// Weights for pallet_shielded_pool using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ShieldedPool::MerkleRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalance` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:1)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::Deposits` (r:0 w:1)
	/// Proof: `ShieldedPool::Deposits` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRoots` (r:0 w:1)
	/// Proof: `ShieldedPool::HistoricRoots` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn shield() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3581`
		// Minimum execution time: 60_000_000 picoseconds.
		Weight::from_parts(61_000_000, 3581)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `ShieldedPool::HistoricRoots` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRoots` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::NullifierSet` (r:1 w:1)
	/// Proof: `ShieldedPool::NullifierSet` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn private_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `355`
		//  Estimated: `3517`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(34_000_000, 3517)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `ShieldedPool::HistoricRoots` (r:1 w:0)
	/// Proof: `ShieldedPool::HistoricRoots` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::NullifierSet` (r:1 w:1)
	/// Proof: `ShieldedPool::NullifierSet` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalance` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn unshield() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `6172`
		// Minimum execution time: 52_000_000 picoseconds.
		Weight::from_parts(52_000_000, 6172)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	fn set_disclosure_verifying_key() -> Weight {
		Weight::from_parts(150_000, 0).saturating_add(T::DbWeight::get().writes(1))
	}
	fn set_audit_policy() -> Weight {
		Weight::from_parts(100_000, 0).saturating_add(T::DbWeight::get().writes(1))
	}
	fn request_disclosure() -> Weight {
		Weight::from_parts(50_000, 0).saturating_add(T::DbWeight::get().reads_writes(2, 1))
	}
	fn approve_disclosure() -> Weight {
		Weight::from_parts(200_000, 0).saturating_add(T::DbWeight::get().reads_writes(3, 2))
	}
	fn reject_disclosure() -> Weight {
		Weight::from_parts(30_000, 0).saturating_add(T::DbWeight::get().writes(1))
	}
	fn submit_disclosure() -> Weight {
		Weight::from_parts(500_000, 0).saturating_add(T::DbWeight::get().reads_writes(4, 2))
	}
	fn batch_submit_disclosure_proofs(n: u32) -> Weight {
		// Base cost for 1 proof is ~500k.
		// With pairing batching, subsequent proofs are much cheaper.
		// Formula: base_verified + (n-1) * optimized_verified + per_submission_storage
		let base_weight = 500_000;
		let optimized_weight = 150_000; // ~70% reduction for subsequent pairings
		Weight::from_parts(base_weight, 0)
			.saturating_add(Weight::from_parts(optimized_weight, 0).saturating_mul((n.saturating_sub(1)) as u64))
			.saturating_add(T::DbWeight::get().reads_writes(n as u64 * 3, n as u64 * 2))
	}
	fn shield_batch(n: u32) -> Weight {
		Weight::from_parts(61_000_000, 3581)
			.saturating_mul(n as u64)
			.saturating_mul(4).saturating_div(5)
			.saturating_add(T::DbWeight::get().reads(n as u64 * 9))
			.saturating_add(T::DbWeight::get().writes(n as u64 * 9))
	}
	fn register_asset() -> Weight {
		Weight::from_parts(100_000, 0).saturating_add(T::DbWeight::get().reads_writes(1, 2))
	}
	fn verify_asset() -> Weight {
		Weight::from_parts(50_000, 0).saturating_add(T::DbWeight::get().reads_writes(1, 1))
	}
	fn unverify_asset() -> Weight {
		Weight::from_parts(50_000, 0).saturating_add(T::DbWeight::get().reads_writes(1, 1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ShieldedPool::MerkleRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalance` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:1)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::Deposits` (r:0 w:1)
	/// Proof: `ShieldedPool::Deposits` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRoots` (r:0 w:1)
	/// Proof: `ShieldedPool::HistoricRoots` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn shield() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3581`
		// Minimum execution time: 60_000_000 picoseconds.
		Weight::from_parts(61_000_000, 3581)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: `ShieldedPool::HistoricRoots` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRoots` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::NullifierSet` (r:1 w:1)
	/// Proof: `ShieldedPool::NullifierSet` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn private_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `355`
		//  Estimated: `3517`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(34_000_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `ShieldedPool::HistoricRoots` (r:1 w:0)
	/// Proof: `ShieldedPool::HistoricRoots` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::NullifierSet` (r:1 w:1)
	/// Proof: `ShieldedPool::NullifierSet` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalance` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn unshield() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `6172`
		// Minimum execution time: 52_000_000 picoseconds.
		Weight::from_parts(52_000_000, 6172)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	fn set_disclosure_verifying_key() -> Weight {
		Weight::from_parts(150_000, 0).saturating_add(RocksDbWeight::get().writes(1))
	}
	fn set_audit_policy() -> Weight {
		Weight::from_parts(100_000, 0).saturating_add(RocksDbWeight::get().writes(1))
	}
	fn request_disclosure() -> Weight {
		Weight::from_parts(50_000, 0).saturating_add(RocksDbWeight::get().reads_writes(2, 1))
	}
	fn approve_disclosure() -> Weight {
		Weight::from_parts(200_000, 0).saturating_add(RocksDbWeight::get().reads_writes(3, 2))
	}
	fn reject_disclosure() -> Weight {
		Weight::from_parts(30_000, 0).saturating_add(RocksDbWeight::get().writes(1))
	}
	fn submit_disclosure() -> Weight {
		Weight::from_parts(500_000, 0).saturating_add(RocksDbWeight::get().reads_writes(4, 2))
	}
	fn batch_submit_disclosure_proofs(n: u32) -> Weight {
		let base_weight = 500_000;
		let optimized_weight = 150_000;
		Weight::from_parts(base_weight, 0)
			.saturating_add(Weight::from_parts(optimized_weight, 0).saturating_mul((n.saturating_sub(1)) as u64))
			.saturating_add(RocksDbWeight::get().reads_writes(n as u64 * 3, n as u64 * 2))
	}
	fn shield_batch(n: u32) -> Weight {
		Weight::from_parts(61_000_000, 3581)
			.saturating_mul(n as u64)
			.saturating_mul(4).saturating_div(5)
			.saturating_add(RocksDbWeight::get().reads(n as u64 * 9))
			.saturating_add(RocksDbWeight::get().writes(n as u64 * 9))
	}
	fn register_asset() -> Weight {
		Weight::from_parts(100_000, 0).saturating_add(RocksDbWeight::get().reads_writes(1, 2))
	}
	fn verify_asset() -> Weight {
		Weight::from_parts(50_000, 0).saturating_add(RocksDbWeight::get().reads_writes(1, 1))
	}
	fn unverify_asset() -> Weight {
		Weight::from_parts(50_000, 0).saturating_add(RocksDbWeight::get().reads_writes(1, 1))
	}
}
