
//! Autogenerated weights for pallet_shielded_pool
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-08-05, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-1`, CPU: `AMD EPYC-Genoa Processor`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/orbinum-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_shielded_pool
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./frame/shielded-pool/src/weights.rs
// --template
// ./scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_shielded_pool.
pub trait WeightInfo {
	fn shield() -> Weight;
	fn shield_batch(n: u32, ) -> Weight;
	fn private_transfer(n: u32, ) -> Weight;
	fn unshield() -> Weight;
	fn register_asset() -> Weight;
	fn verify_asset() -> Weight;
	fn unverify_asset() -> Weight;
	fn claim_shielded_fees() -> Weight;
	/// Weight of one `on_idle` sealed-tree sweep that removes `n` nodes.
	///
	/// Both impls below are PLACEHOLDERS derived from storage-access counts, not
	/// measured. Replace with generated weights before a chain seals its first
	/// tree; until then nothing is pruned, so the estimate goes unused.
	fn prune_sealed_nodes(n: u32) -> Weight;
}

/// Weights for pallet_shielded_pool using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentMemos` (r:1 w:1)
	/// Proof: `ShieldedPool::CommitmentMemos` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeFrontier` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeFrontier` (`max_values`: Some(1), `max_size`: Some(640), added: 1135, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalCommitmentsInserted` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalCommitmentsInserted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsHead` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsTail` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsQueue` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsQueue` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalancePerAsset` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalancePerAsset` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleNodes` (r:0 w:19)
	/// Proof: `ShieldedPool::MerkleNodes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:1)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentToLeafIndex` (r:0 w:1)
	/// Proof: `ShieldedPool::CommitmentToLeafIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn shield() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1242`
		//  Estimated: `3695`
		// Minimum execution time: 861_716_000 picoseconds.
		Weight::from_parts(878_209_000, 3695)
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(34_u64))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentMemos` (r:20 w:20)
	/// Proof: `ShieldedPool::CommitmentMemos` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeFrontier` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeFrontier` (`max_values`: Some(1), `max_size`: Some(640), added: 1135, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalCommitmentsInserted` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalCommitmentsInserted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsHead` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsTail` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsQueue` (r:1 w:20)
	/// Proof: `ShieldedPool::HistoricRootsQueue` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:20 w:20)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalancePerAsset` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalancePerAsset` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleNodes` (r:0 w:35)
	/// Proof: `ShieldedPool::MerkleNodes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:20)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentToLeafIndex` (r:0 w:20)
	/// Proof: `ShieldedPool::CommitmentToLeafIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn shield_batch(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1242`
		//  Estimated: `3631 + n * (2705 ±0)`
		// Minimum execution time: 853_004_000 picoseconds.
		Weight::from_parts(77_406_360, 3631)
			// Standard Error: 2_015_265
			.saturating_add(Weight::from_parts(851_634_513, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(15_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(27_u64))
			.saturating_add(T::DbWeight::get().writes((6_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2705).saturating_mul(n.into()))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:3 w:2)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::NullifierSet` (r:2 w:2)
	/// Proof: `ShieldedPool::NullifierSet` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::MinRelayFee` (r:1 w:0)
	/// Proof: `Relayer::MinRelayFee` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalNullifiersSpent` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalNullifiersSpent` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentMemos` (r:2 w:2)
	/// Proof: `ShieldedPool::CommitmentMemos` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeFrontier` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeFrontier` (`max_values`: Some(1), `max_size`: Some(640), added: 1135, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalCommitmentsInserted` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalCommitmentsInserted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsHead` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsTail` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsQueue` (r:1 w:2)
	/// Proof: `ShieldedPool::HistoricRootsQueue` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::RelayerRegistry` (r:1 w:0)
	/// Proof: `Relayer::RelayerRegistry` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::PendingRelayerFees` (r:1 w:1)
	/// Proof: `Relayer::PendingRelayerFees` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleNodes` (r:0 w:19)
	/// Proof: `ShieldedPool::MerkleNodes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:2)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentToLeafIndex` (r:0 w:2)
	/// Proof: `ShieldedPool::CommitmentToLeafIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 2]`.
	fn private_transfer(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1260`
		//  Estimated: `3631 + n * (2705 ±0)`
		// Minimum execution time: 829_842_000 picoseconds.
		Weight::from_parts(58_727_597, 3631)
			// Standard Error: 3_711_290
			.saturating_add(Weight::from_parts(813_265_051, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(29_u64))
			.saturating_add(T::DbWeight::get().writes((6_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2705).saturating_mul(n.into()))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:0)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:1 w:0)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::NullifierSet` (r:1 w:1)
	/// Proof: `ShieldedPool::NullifierSet` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalancePerAsset` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalancePerAsset` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::MinRelayFee` (r:1 w:0)
	/// Proof: `Relayer::MinRelayFee` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::RelayerRegistry` (r:1 w:0)
	/// Proof: `Relayer::RelayerRegistry` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::PendingRelayerFees` (r:1 w:1)
	/// Proof: `Relayer::PendingRelayerFees` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalNullifiersSpent` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalNullifiersSpent` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn unshield() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `6196`
		// Minimum execution time: 108_500_000 picoseconds.
		Weight::from_parts(112_414_000, 6196)
			.saturating_add(T::DbWeight::get().reads(16_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `ShieldedPool::NextAssetId` (r:1 w:1)
	/// Proof: `ShieldedPool::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::Assets` (r:1 w:1)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3631`
		// Minimum execution time: 16_953_000 picoseconds.
		Weight::from_parts(17_543_000, 3631)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:1)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn verify_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349`
		//  Estimated: `3631`
		// Minimum execution time: 17_044_000 picoseconds.
		Weight::from_parts(17_754_000, 3631)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:1)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn unverify_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349`
		//  Estimated: `3631`
		// Minimum execution time: 16_913_000 picoseconds.
		Weight::from_parts(17_645_000, 3631)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::PendingRelayerFees` (r:1 w:1)
	/// Proof: `Relayer::PendingRelayerFees` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentMemos` (r:1 w:1)
	/// Proof: `ShieldedPool::CommitmentMemos` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeFrontier` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeFrontier` (`max_values`: Some(1), `max_size`: Some(640), added: 1135, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalCommitmentsInserted` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalCommitmentsInserted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsHead` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsTail` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsQueue` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsQueue` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleNodes` (r:0 w:19)
	/// Proof: `ShieldedPool::MerkleNodes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:1)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentToLeafIndex` (r:0 w:1)
	/// Proof: `ShieldedPool::CommitmentToLeafIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn claim_shielded_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1200`
		//  Estimated: `3695`
		// Minimum execution time: 841_328_000 picoseconds.
		Weight::from_parts(851_813_000, 3695)
			.saturating_add(T::DbWeight::get().reads(15_u64))
			.saturating_add(T::DbWeight::get().writes(33_u64))
	}
	/// PLACEHOLDER: cursor read, then one keyed read plus one removal per node.
	fn prune_sealed_nodes(n: u32) -> Weight {
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads_writes(1_u64, 1_u64).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentMemos` (r:1 w:1)
	/// Proof: `ShieldedPool::CommitmentMemos` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeFrontier` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeFrontier` (`max_values`: Some(1), `max_size`: Some(640), added: 1135, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalCommitmentsInserted` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalCommitmentsInserted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsHead` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsTail` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsQueue` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsQueue` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalancePerAsset` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalancePerAsset` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleNodes` (r:0 w:19)
	/// Proof: `ShieldedPool::MerkleNodes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:1)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentToLeafIndex` (r:0 w:1)
	/// Proof: `ShieldedPool::CommitmentToLeafIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn shield() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1242`
		//  Estimated: `3695`
		// Minimum execution time: 861_716_000 picoseconds.
		Weight::from_parts(878_209_000, 3695)
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(34_u64))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentMemos` (r:20 w:20)
	/// Proof: `ShieldedPool::CommitmentMemos` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeFrontier` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeFrontier` (`max_values`: Some(1), `max_size`: Some(640), added: 1135, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalCommitmentsInserted` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalCommitmentsInserted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsHead` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsTail` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsQueue` (r:1 w:20)
	/// Proof: `ShieldedPool::HistoricRootsQueue` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:20 w:20)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalancePerAsset` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalancePerAsset` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleNodes` (r:0 w:35)
	/// Proof: `ShieldedPool::MerkleNodes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:20)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentToLeafIndex` (r:0 w:20)
	/// Proof: `ShieldedPool::CommitmentToLeafIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn shield_batch(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1242`
		//  Estimated: `3631 + n * (2705 ±0)`
		// Minimum execution time: 853_004_000 picoseconds.
		Weight::from_parts(77_406_360, 3631)
			// Standard Error: 2_015_265
			.saturating_add(Weight::from_parts(851_634_513, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(15_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(27_u64))
			.saturating_add(RocksDbWeight::get().writes((6_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2705).saturating_mul(n.into()))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:3 w:2)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::NullifierSet` (r:2 w:2)
	/// Proof: `ShieldedPool::NullifierSet` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::MinRelayFee` (r:1 w:0)
	/// Proof: `Relayer::MinRelayFee` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalNullifiersSpent` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalNullifiersSpent` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentMemos` (r:2 w:2)
	/// Proof: `ShieldedPool::CommitmentMemos` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeFrontier` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeFrontier` (`max_values`: Some(1), `max_size`: Some(640), added: 1135, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalCommitmentsInserted` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalCommitmentsInserted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsHead` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsTail` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsQueue` (r:1 w:2)
	/// Proof: `ShieldedPool::HistoricRootsQueue` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::RelayerRegistry` (r:1 w:0)
	/// Proof: `Relayer::RelayerRegistry` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::PendingRelayerFees` (r:1 w:1)
	/// Proof: `Relayer::PendingRelayerFees` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleNodes` (r:0 w:19)
	/// Proof: `ShieldedPool::MerkleNodes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:2)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentToLeafIndex` (r:0 w:2)
	/// Proof: `ShieldedPool::CommitmentToLeafIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 2]`.
	fn private_transfer(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1260`
		//  Estimated: `3631 + n * (2705 ±0)`
		// Minimum execution time: 829_842_000 picoseconds.
		Weight::from_parts(58_727_597, 3631)
			// Standard Error: 3_711_290
			.saturating_add(Weight::from_parts(813_265_051, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(29_u64))
			.saturating_add(RocksDbWeight::get().writes((6_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2705).saturating_mul(n.into()))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:0)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:1 w:0)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::NullifierSet` (r:1 w:1)
	/// Proof: `ShieldedPool::NullifierSet` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoolBalancePerAsset` (r:1 w:1)
	/// Proof: `ShieldedPool::PoolBalancePerAsset` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::MinRelayFee` (r:1 w:0)
	/// Proof: `Relayer::MinRelayFee` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::RelayerRegistry` (r:1 w:0)
	/// Proof: `Relayer::RelayerRegistry` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::PendingRelayerFees` (r:1 w:1)
	/// Proof: `Relayer::PendingRelayerFees` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalNullifiersSpent` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalNullifiersSpent` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn unshield() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `6196`
		// Minimum execution time: 108_500_000 picoseconds.
		Weight::from_parts(112_414_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(16_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `ShieldedPool::NextAssetId` (r:1 w:1)
	/// Proof: `ShieldedPool::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::Assets` (r:1 w:1)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3631`
		// Minimum execution time: 16_953_000 picoseconds.
		Weight::from_parts(17_543_000, 3631)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:1)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn verify_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349`
		//  Estimated: `3631`
		// Minimum execution time: 17_044_000 picoseconds.
		Weight::from_parts(17_754_000, 3631)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:1)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn unverify_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349`
		//  Estimated: `3631`
		// Minimum execution time: 16_913_000 picoseconds.
		Weight::from_parts(17_645_000, 3631)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ShieldedPool::Assets` (r:1 w:0)
	/// Proof: `ShieldedPool::Assets` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Relayer::PendingRelayerFees` (r:1 w:1)
	/// Proof: `Relayer::PendingRelayerFees` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ShieldedPool::MerkleTreeSize` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentMemos` (r:1 w:1)
	/// Proof: `ShieldedPool::CommitmentMemos` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleTreeFrontier` (r:1 w:1)
	/// Proof: `ShieldedPool::MerkleTreeFrontier` (`max_values`: Some(1), `max_size`: Some(640), added: 1135, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::PoseidonRoot` (r:1 w:1)
	/// Proof: `ShieldedPool::PoseidonRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::TotalCommitmentsInserted` (r:1 w:1)
	/// Proof: `ShieldedPool::TotalCommitmentsInserted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsHead` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsTail` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricRootsQueue` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricRootsQueue` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::HistoricPoseidonRoots` (r:1 w:1)
	/// Proof: `ShieldedPool::HistoricPoseidonRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleNodes` (r:0 w:19)
	/// Proof: `ShieldedPool::MerkleNodes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::MerkleLeaves` (r:0 w:1)
	/// Proof: `ShieldedPool::MerkleLeaves` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ShieldedPool::CommitmentToLeafIndex` (r:0 w:1)
	/// Proof: `ShieldedPool::CommitmentToLeafIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn claim_shielded_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1200`
		//  Estimated: `3695`
		// Minimum execution time: 841_328_000 picoseconds.
		Weight::from_parts(851_813_000, 3695)
			.saturating_add(RocksDbWeight::get().reads(15_u64))
			.saturating_add(RocksDbWeight::get().writes(33_u64))
	}
	/// PLACEHOLDER: cursor read, then one keyed read plus one removal per node.
	fn prune_sealed_nodes(n: u32) -> Weight {
		Weight::from_parts(5_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().reads_writes(1_u64, 1_u64).saturating_mul(n.into()))
	}
}
