//! Auto-generated Verification Key for transfer circuit
//! Generated by: ./scripts/update-vk.sh
//! Source: circuits/build/transfer_vk.json
//!
//! DO NOT EDIT MANUALLY - Run the update-vk.sh script to regenerate

use alloc::vec;
use ark_bn254::{Bn254, Fq, Fq2, G1Affine, G2Affine};
use ark_groth16::VerifyingKey;
use ark_serialize::CanonicalSerialize;
use ark_std::str::FromStr;

use crate::core::constants::{CIRCUIT_ID_TRANSFER, TRANSFER_PUBLIC_INPUTS};

/// Circuit ID for transfer (re-exported from core)
pub const CIRCUIT_ID: u8 = CIRCUIT_ID_TRANSFER;

/// Number of public inputs for this circuit (re-exported from core)
pub const NUM_PUBLIC_INPUTS: usize = TRANSFER_PUBLIC_INPUTS;

/// Creates the verification key for the transfer circuit
pub fn get_vk() -> VerifyingKey<Bn254> {
	// Alpha G1
	let alpha_g1 = G1Affine::new_unchecked(
		Fq::from_str(
			"20491192805390485299153009773594534940189261866228447918068658471970481763042",
		)
		.unwrap(),
		Fq::from_str(
			"9383485363053290200918347156157836566562967994039712273449902621266178545958",
		)
		.unwrap(),
	);

	// Beta G2
	let beta_g2 = G2Affine::new_unchecked(
		Fq2::new(
			Fq::from_str(
				"6375614351688725206403948262868962793625744043794305715222011528459656738731",
			)
			.unwrap(),
			Fq::from_str(
				"4252822878758300859123897981450591353533073413197771768651442665752259397132",
			)
			.unwrap(),
		),
		Fq2::new(
			Fq::from_str(
				"10505242626370262277552901082094356697409835680220590971873171140371331206856",
			)
			.unwrap(),
			Fq::from_str(
				"21847035105528745403288232691147584728191162732299865338377159692350059136679",
			)
			.unwrap(),
		),
	);

	// Gamma G2
	let gamma_g2 = G2Affine::new_unchecked(
		Fq2::new(
			Fq::from_str(
				"10857046999023057135944570762232829481370756359578518086990519993285655852781",
			)
			.unwrap(),
			Fq::from_str(
				"11559732032986387107991004021392285783925812861821192530917403151452391805634",
			)
			.unwrap(),
		),
		Fq2::new(
			Fq::from_str(
				"8495653923123431417604973247489272438418190587263600148770280649306958101930",
			)
			.unwrap(),
			Fq::from_str(
				"4082367875863433681332203403145435568316851327593401208105741076214120093531",
			)
			.unwrap(),
		),
	);

	// Delta G2
	let delta_g2 = G2Affine::new_unchecked(
		Fq2::new(
			Fq::from_str(
				"13290579243035896667219352853260954451540683351463684060643954052001846090360",
			)
			.unwrap(),
			Fq::from_str(
				"6853261065573673850129290616062663630341504236970379210332122173515343726588",
			)
			.unwrap(),
		),
		Fq2::new(
			Fq::from_str(
				"2338865429356301623557892669253612693011879622928827409089829745812163954355",
			)
			.unwrap(),
			Fq::from_str(
				"16697356877137411137859866590077982554992654222189305141230110215420016338624",
			)
			.unwrap(),
		),
	);

	// IC points (gamma_abc_g1)
	let ic_0 = G1Affine::new_unchecked(
		Fq::from_str(
			"6387311796876663656069926386878587314798354473208527984695427072999290738193",
		)
		.unwrap(),
		Fq::from_str(
			"3217769572252563949795473227174610859855396572440179800692706784079504642089",
		)
		.unwrap(),
	);

	let ic_1 = G1Affine::new_unchecked(
		Fq::from_str(
			"8055162832968171088489865347079214482470259565891225397675091673356244995187",
		)
		.unwrap(),
		Fq::from_str(
			"8109909669694983518828643732974229274761128133245294376977521335233727128540",
		)
		.unwrap(),
	);

	let ic_2 = G1Affine::new_unchecked(
		Fq::from_str(
			"3730217927801120990889635207478509842485214259114924972749080154711818248312",
		)
		.unwrap(),
		Fq::from_str(
			"3924289260988281376847768525967642969684434709932037682261199189861440083601",
		)
		.unwrap(),
	);

	let ic_3 = G1Affine::new_unchecked(
		Fq::from_str(
			"7679285704971676971868456231781662597376001650049506021213269295950245809049",
		)
		.unwrap(),
		Fq::from_str(
			"20195789704465200839592016308194536043229558176568382093466259072457224603068",
		)
		.unwrap(),
	);

	let ic_4 = G1Affine::new_unchecked(
		Fq::from_str(
			"8175059342946583279509771314656137728529570201167315055933238257296251197138",
		)
		.unwrap(),
		Fq::from_str(
			"11485234397321140102852695688040267204393927813635284918495011375993135610513",
		)
		.unwrap(),
	);

	let ic_5 = G1Affine::new_unchecked(
		Fq::from_str(
			"5944939212375763077627862507655071066889887939132607506789531064499405331888",
		)
		.unwrap(),
		Fq::from_str(
			"1361848952758603075398007776435033197205330314625141168783286829868053182081",
		)
		.unwrap(),
	);

	let gamma_abc_g1 = vec![ic_0, ic_1, ic_2, ic_3, ic_4, ic_5];

	VerifyingKey {
		alpha_g1,
		beta_g2,
		gamma_g2,
		delta_g2,
		gamma_abc_g1,
	}
}

/// Returns the verification key as compressed bytes for genesis/storage
pub fn get_vk_bytes() -> alloc::vec::Vec<u8> {
	let vk = get_vk();
	let mut bytes = alloc::vec::Vec::new();
	vk.serialize_compressed(&mut bytes)
		.expect("VK serialization should not fail");
	bytes
}
