//! Auto-generated Verification Key for unshield circuit
//! Generated by: ./scripts/update-vk.sh
//! Source: circuits/build/unshield_vk.json
//!
//! DO NOT EDIT MANUALLY - Run the update-vk.sh script to regenerate

use alloc::vec;
use ark_bn254::{Bn254, Fq, Fq2, G1Affine, G2Affine};
use ark_groth16::VerifyingKey;
use ark_serialize::CanonicalSerialize;
use ark_std::str::FromStr;

use crate::core::constants::{CIRCUIT_ID_UNSHIELD, UNSHIELD_PUBLIC_INPUTS};

/// Circuit ID for unshield (re-exported from core)
pub const CIRCUIT_ID: u8 = CIRCUIT_ID_UNSHIELD;

/// Number of public inputs for this circuit (re-exported from core)
pub const NUM_PUBLIC_INPUTS: usize = UNSHIELD_PUBLIC_INPUTS;

/// Creates the verification key for the unshield circuit
pub fn get_vk() -> VerifyingKey<Bn254> {
	// Alpha G1
	let alpha_g1 = G1Affine::new_unchecked(
		Fq::from_str(
			"20491192805390485299153009773594534940189261866228447918068658471970481763042",
		)
		.unwrap(),
		Fq::from_str(
			"9383485363053290200918347156157836566562967994039712273449902621266178545958",
		)
		.unwrap(),
	);

	// Beta G2
	let beta_g2 = G2Affine::new_unchecked(
		Fq2::new(
			Fq::from_str(
				"6375614351688725206403948262868962793625744043794305715222011528459656738731",
			)
			.unwrap(),
			Fq::from_str(
				"4252822878758300859123897981450591353533073413197771768651442665752259397132",
			)
			.unwrap(),
		),
		Fq2::new(
			Fq::from_str(
				"10505242626370262277552901082094356697409835680220590971873171140371331206856",
			)
			.unwrap(),
			Fq::from_str(
				"21847035105528745403288232691147584728191162732299865338377159692350059136679",
			)
			.unwrap(),
		),
	);

	// Gamma G2
	let gamma_g2 = G2Affine::new_unchecked(
		Fq2::new(
			Fq::from_str(
				"10857046999023057135944570762232829481370756359578518086990519993285655852781",
			)
			.unwrap(),
			Fq::from_str(
				"11559732032986387107991004021392285783925812861821192530917403151452391805634",
			)
			.unwrap(),
		),
		Fq2::new(
			Fq::from_str(
				"8495653923123431417604973247489272438418190587263600148770280649306958101930",
			)
			.unwrap(),
			Fq::from_str(
				"4082367875863433681332203403145435568316851327593401208105741076214120093531",
			)
			.unwrap(),
		),
	);

	// Delta G2
	let delta_g2 = G2Affine::new_unchecked(
		Fq2::new(
			Fq::from_str(
				"21270721013896835491037368009844451669135670642567281526505283391881738205217",
			)
			.unwrap(),
			Fq::from_str(
				"14538782267225887760543564059182091364414590714483001155786189192273814568976",
			)
			.unwrap(),
		),
		Fq2::new(
			Fq::from_str(
				"21000878769436047459920785198056869479985495398920904936873229787297459831882",
			)
			.unwrap(),
			Fq::from_str(
				"2536136645620278574193474357321243298563892023873927019148839199823453113318",
			)
			.unwrap(),
		),
	);

	// IC points (gamma_abc_g1)
	let ic_0 = G1Affine::new_unchecked(
		Fq::from_str(
			"20916236017396229065730168171921531540219883693816649527473756210941483256437",
		)
		.unwrap(),
		Fq::from_str(
			"5994336072425495010535505484672090175979281754500974128060906944705318076819",
		)
		.unwrap(),
	);

	let ic_1 = G1Affine::new_unchecked(
		Fq::from_str(
			"9548773269773859569757852893401892397147895125275077909360924522809308527015",
		)
		.unwrap(),
		Fq::from_str(
			"10371785129828005987182550782584463122609323812790595045656932591934008034167",
		)
		.unwrap(),
	);

	let ic_2 = G1Affine::new_unchecked(
		Fq::from_str(
			"19086302161291521108529769563147876912066886600766788035786164869026460277240",
		)
		.unwrap(),
		Fq::from_str(
			"16095703331208149406202939748928974065803466072520406582138943694892986976364",
		)
		.unwrap(),
	);

	let ic_3 = G1Affine::new_unchecked(
		Fq::from_str(
			"7336600832515091657716737232031248908139132084504091968450648444788343938403",
		)
		.unwrap(),
		Fq::from_str(
			"2608486211861212680390579284083957476651698935048160317463605210490589037377",
		)
		.unwrap(),
	);

	let ic_4 = G1Affine::new_unchecked(
		Fq::from_str(
			"3406974973993009703657333869680628836791053675214160878555753432204217563459",
		)
		.unwrap(),
		Fq::from_str(
			"7081951346060232336862906852673304735653403199530497301749621251335967909075",
		)
		.unwrap(),
	);

	let gamma_abc_g1 = vec![ic_0, ic_1, ic_2, ic_3, ic_4];

	VerifyingKey {
		alpha_g1,
		beta_g2,
		gamma_g2,
		delta_g2,
		gamma_abc_g1,
	}
}

/// Returns the verification key as compressed bytes for genesis/storage
pub fn get_vk_bytes() -> alloc::vec::Vec<u8> {
	let vk = get_vk();
	let mut bytes = alloc::vec::Vec::new();
	vk.serialize_compressed(&mut bytes)
		.expect("VK serialization should not fail");
	bytes
}
