
//! Autogenerated weights for pallet_account_mapping
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-06-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-hil-1`, CPU: `AMD EPYC-Milan Processor`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/orbinum-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_account_mapping
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./frame/account-mapping/src/weights.rs
// --template
// ./scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_account_mapping.
pub trait WeightInfo {
	fn map_account() -> Weight;
	fn unmap_account() -> Weight;
	fn register_alias() -> Weight;
	fn release_alias() -> Weight;
	fn transfer_alias() -> Weight;
	fn put_alias_on_sale() -> Weight;
	fn cancel_sale() -> Weight;
	fn buy_alias() -> Weight;
	fn add_chain_link() -> Weight;
	fn remove_chain_link() -> Weight;
	fn set_account_metadata() -> Weight;
	fn dispatch_as_linked_account() -> Weight;
	fn register_private_link() -> Weight;
	fn remove_private_link() -> Weight;
	fn reveal_private_link() -> Weight;
	fn dispatch_as_private_link() -> Weight;
}

/// Weights for pallet_account_mapping using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn map_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 7_211_000 picoseconds.
		Weight::from_parts(7_601_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AccountMapping::OriginalAccounts` (r:1 w:1)
	/// Proof: `AccountMapping::OriginalAccounts` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::MappedAccounts` (r:0 w:1)
	/// Proof: `AccountMapping::MappedAccounts` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn unmap_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `189`
		//  Estimated: `3533`
		// Minimum execution time: 14_482_000 picoseconds.
		Weight::from_parts(14_742_000, 3533)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:1)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `5728`
		// Minimum execution time: 32_749_000 picoseconds.
		Weight::from_parts(33_460_000, 5728)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:1)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:0 w:1)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:0 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	fn release_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `257`
		//  Estimated: `5728`
		// Minimum execution time: 35_825_000 picoseconds.
		Weight::from_parts(36_775_000, 5728)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:2 w:2)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:0 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	fn transfer_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `360`
		//  Estimated: `6102`
		// Minimum execution time: 57_768_000 picoseconds.
		Weight::from_parts(58_910_000, 6102)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:1 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn put_alias_on_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `186`
		//  Estimated: `4172`
		// Minimum execution time: 17_226_000 picoseconds.
		Weight::from_parts(17_667_000, 4172)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:1 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn cancel_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `4172`
		// Minimum execution time: 18_328_000 picoseconds.
		Weight::from_parts(18_728_000, 4172)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:2)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:1 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn buy_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `512`
		//  Estimated: `5728`
		// Minimum execution time: 103_616_000 picoseconds.
		Weight::from_parts(105_290_000, 5728)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::SupportedChains` (r:1 w:0)
	/// Proof: `AccountMapping::SupportedChains` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::ReverseChainLinks` (r:0 w:1)
	/// Proof: `AccountMapping::ReverseChainLinks` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	fn add_chain_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299`
		//  Estimated: `5728`
		// Minimum execution time: 60_913_000 picoseconds.
		Weight::from_parts(62_305_000, 5728)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::ReverseChainLinks` (r:0 w:1)
	/// Proof: `AccountMapping::ReverseChainLinks` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	fn remove_chain_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `286`
		//  Estimated: `5728`
		// Minimum execution time: 20_981_000 picoseconds.
		Weight::from_parts(21_532_000, 5728)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::AccountMetadatas` (r:0 w:1)
	/// Proof: `AccountMapping::AccountMetadatas` (`max_values`: None, `max_size`: Some(441), added: 2916, mode: `MaxEncodedLen`)
	fn set_account_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `186`
		//  Estimated: `3546`
		// Minimum execution time: 15_444_000 picoseconds.
		Weight::from_parts(15_984_000, 3546)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::ReverseChainLinks` (r:1 w:0)
	/// Proof: `AccountMapping::ReverseChainLinks` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::SupportedChains` (r:1 w:0)
	/// Proof: `AccountMapping::SupportedChains` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn dispatch_as_linked_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3647`
		// Minimum execution time: 55_194_000 picoseconds.
		Weight::from_parts(56_225_000, 3647)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:1 w:1)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_private_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `237`
		//  Estimated: `4091`
		// Minimum execution time: 18_478_000 picoseconds.
		Weight::from_parts(19_209_000, 4091)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:1 w:1)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn remove_private_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281`
		//  Estimated: `4091`
		// Minimum execution time: 19_679_000 picoseconds.
		Weight::from_parts(20_021_000, 4091)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:1 w:1)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::SupportedChains` (r:1 w:0)
	/// Proof: `AccountMapping::SupportedChains` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::ReverseChainLinks` (r:0 w:1)
	/// Proof: `AccountMapping::ReverseChainLinks` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	fn reveal_private_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `393`
		//  Estimated: `5728`
		// Minimum execution time: 123_198_000 picoseconds.
		Weight::from_parts(124_228_000, 5728)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:1 w:0)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn dispatch_as_private_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281`
		//  Estimated: `4091`
		// Minimum execution time: 20_280_000 picoseconds.
		Weight::from_parts(20_913_000, 4091)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn map_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 7_211_000 picoseconds.
		Weight::from_parts(7_601_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AccountMapping::OriginalAccounts` (r:1 w:1)
	/// Proof: `AccountMapping::OriginalAccounts` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::MappedAccounts` (r:0 w:1)
	/// Proof: `AccountMapping::MappedAccounts` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn unmap_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `189`
		//  Estimated: `3533`
		// Minimum execution time: 14_482_000 picoseconds.
		Weight::from_parts(14_742_000, 3533)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:1)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `5728`
		// Minimum execution time: 32_749_000 picoseconds.
		Weight::from_parts(33_460_000, 5728)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:1)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:0 w:1)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:0 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	fn release_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `257`
		//  Estimated: `5728`
		// Minimum execution time: 35_825_000 picoseconds.
		Weight::from_parts(36_775_000, 5728)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:2 w:2)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:0 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	fn transfer_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `360`
		//  Estimated: `6102`
		// Minimum execution time: 57_768_000 picoseconds.
		Weight::from_parts(58_910_000, 6102)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:1 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn put_alias_on_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `186`
		//  Estimated: `4172`
		// Minimum execution time: 17_226_000 picoseconds.
		Weight::from_parts(17_667_000, 4172)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:1 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn cancel_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `4172`
		// Minimum execution time: 18_328_000 picoseconds.
		Weight::from_parts(18_728_000, 4172)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:2)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::AliasListings` (r:1 w:1)
	/// Proof: `AccountMapping::AliasListings` (`max_values`: None, `max_size`: Some(707), added: 3182, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn buy_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `512`
		//  Estimated: `5728`
		// Minimum execution time: 103_616_000 picoseconds.
		Weight::from_parts(105_290_000, 5728)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::SupportedChains` (r:1 w:0)
	/// Proof: `AccountMapping::SupportedChains` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::ReverseChainLinks` (r:0 w:1)
	/// Proof: `AccountMapping::ReverseChainLinks` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	fn add_chain_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299`
		//  Estimated: `5728`
		// Minimum execution time: 60_913_000 picoseconds.
		Weight::from_parts(62_305_000, 5728)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::ReverseChainLinks` (r:0 w:1)
	/// Proof: `AccountMapping::ReverseChainLinks` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	fn remove_chain_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `286`
		//  Estimated: `5728`
		// Minimum execution time: 20_981_000 picoseconds.
		Weight::from_parts(21_532_000, 5728)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::AccountMetadatas` (r:0 w:1)
	/// Proof: `AccountMapping::AccountMetadatas` (`max_values`: None, `max_size`: Some(441), added: 2916, mode: `MaxEncodedLen`)
	fn set_account_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `186`
		//  Estimated: `3546`
		// Minimum execution time: 15_444_000 picoseconds.
		Weight::from_parts(15_984_000, 3546)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::ReverseChainLinks` (r:1 w:0)
	/// Proof: `AccountMapping::ReverseChainLinks` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::SupportedChains` (r:1 w:0)
	/// Proof: `AccountMapping::SupportedChains` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn dispatch_as_linked_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3647`
		// Minimum execution time: 55_194_000 picoseconds.
		Weight::from_parts(56_225_000, 3647)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:1 w:1)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_private_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `237`
		//  Estimated: `4091`
		// Minimum execution time: 18_478_000 picoseconds.
		Weight::from_parts(19_209_000, 4091)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:1 w:1)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn remove_private_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281`
		//  Estimated: `4091`
		// Minimum execution time: 19_679_000 picoseconds.
		Weight::from_parts(20_021_000, 4091)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:1 w:1)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::SupportedChains` (r:1 w:0)
	/// Proof: `AccountMapping::SupportedChains` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::Identities` (r:1 w:1)
	/// Proof: `AccountMapping::Identities` (`max_values`: None, `max_size`: Some(2263), added: 4738, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountMapping::ReverseChainLinks` (r:0 w:1)
	/// Proof: `AccountMapping::ReverseChainLinks` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	fn reveal_private_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `393`
		//  Estimated: `5728`
		// Minimum execution time: 123_198_000 picoseconds.
		Weight::from_parts(124_228_000, 5728)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `AccountMapping::AccountAliases` (r:1 w:0)
	/// Proof: `AccountMapping::AccountAliases` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AccountMapping::PrivateChainLinks` (r:1 w:0)
	/// Proof: `AccountMapping::PrivateChainLinks` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn dispatch_as_private_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281`
		//  Estimated: `4091`
		// Minimum execution time: 20_280_000 picoseconds.
		Weight::from_parts(20_913_000, 4091)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
