//! Snarkjs format parser
//!
//! This module provides utilities to parse proofs and public inputs from
//! the JSON format generated by snarkjs (the tool used to compile Circom circuits).

#[cfg(feature = "std")]
use crate::{Proof, PublicInputs, VerifierError};

#[cfg(feature = "std")]
use {
	ark_bn254::{Fq, Fq2, G1Affine, G2Affine},
	ark_groth16::Proof as ArkProof,
	num_bigint::BigUint,
};

/// Snarkjs proof points as separate coordinate strings
pub struct SnarkjsProofPoints<'a> {
	pub a_x: &'a str,
	pub a_y: &'a str,
	pub b_x0: &'a str,
	pub b_x1: &'a str,
	pub b_y0: &'a str,
	pub b_y1: &'a str,
	pub c_x: &'a str,
	pub c_y: &'a str,
}

/// Parse a proof from snarkjs JSON format
///
/// The snarkjs format looks like:
/// ```json
/// {
///   "a": { "x": "...", "y": "..." },
///   "b": { "x": ["...", "..."], "y": ["...", "..."] },
///   "c": { "x": "...", "y": "..." }
/// }
/// ```
#[cfg(feature = "std")]
pub fn parse_proof_from_snarkjs(points: SnarkjsProofPoints) -> Result<Proof, VerifierError> {
	use ark_bn254::Bn254;

	// Build points unchecked, then validate on-curve/subgroup — `new` would panic.
	let a = G1Affine::new_unchecked(parse_fq(points.a_x)?, parse_fq(points.a_y)?);
	// snarkjs exports G2 coordinates in [c0, c1] order → Fq2::new(c0, c1).
	let b = G2Affine::new_unchecked(
		Fq2::new(parse_fq(points.b_x0)?, parse_fq(points.b_x1)?),
		Fq2::new(parse_fq(points.b_y0)?, parse_fq(points.b_y1)?),
	);
	let c = G1Affine::new_unchecked(parse_fq(points.c_x)?, parse_fq(points.c_y)?);

	for on_curve in [a.is_on_curve(), b.is_on_curve(), c.is_on_curve()] {
		if !on_curve {
			return Err(VerifierError::InvalidProof);
		}
	}
	if !a.is_in_correct_subgroup_assuming_on_curve()
		|| !b.is_in_correct_subgroup_assuming_on_curve()
		|| !c.is_in_correct_subgroup_assuming_on_curve()
	{
		return Err(VerifierError::InvalidProof);
	}

	Proof::from_ark_proof(&ArkProof::<Bn254> { a, b, c })
}

/// Parse public inputs from snarkjs JSON format
///
/// The format is an array of field element strings:
/// ```json
/// ["123...", "456...", ...]
/// ```
#[cfg(feature = "std")]
pub fn parse_public_inputs_from_snarkjs(
	input_strings: &[&str],
) -> Result<PublicInputs, VerifierError> {
	let fields: Result<Vec<_>, _> = input_strings.iter().map(|s| parse_fr(s)).collect();
	Ok(PublicInputs::from_field_elements(&fields?))
}

/// Parse a decimal string into a field element, rejecting non-canonical values
/// (`>= modulus`). Returns `err` for a non-decimal or out-of-range value, so a
/// coordinate is never silently reduced. Reduction on a `< modulus` value is exact.
#[cfg(feature = "std")]
fn parse_canonical<F: ark_ff::PrimeField>(s: &str, err: VerifierError) -> Result<F, VerifierError> {
	use ark_ff::BigInteger;
	let value = BigUint::parse_bytes(s.as_bytes(), 10).ok_or_else(|| err.clone())?;
	let modulus = BigUint::from_bytes_le(&F::MODULUS.to_bytes_le());
	if value >= modulus {
		return Err(err);
	}
	Ok(F::from_le_bytes_mod_order(&value.to_bytes_le()))
}

#[cfg(feature = "std")]
fn parse_fq(s: &str) -> Result<Fq, VerifierError> {
	parse_canonical(s, VerifierError::InvalidProof)
}

#[cfg(feature = "std")]
fn parse_fr(s: &str) -> Result<ark_bn254::Fr, VerifierError> {
	parse_canonical(s, VerifierError::InvalidPublicInput)
}

#[cfg(all(test, feature = "std"))]
mod tests {
	use super::*;

	// === parse_public_inputs_from_snarkjs Tests ===

	#[test]
	fn test_parse_public_inputs_valid_small_values() {
		let input_strings = ["123", "456", "789"];
		let result = parse_public_inputs_from_snarkjs(&input_strings);
		assert!(result.is_ok(), "Should parse valid inputs");

		let inputs = result.unwrap();
		assert_eq!(inputs.len(), 3);
	}

	#[test]
	fn test_parse_public_inputs_single_value() {
		let inputs = parse_public_inputs_from_snarkjs(&["42"]).unwrap();
		assert_eq!(inputs.len(), 1);
		let fields = inputs.to_field_elements().unwrap();
		assert_eq!(fields[0], ark_bn254::Fr::from(42u64));
	}

	#[test]
	fn test_parse_public_inputs_empty() {
		let input_strings: [&str; 0] = [];
		let result = parse_public_inputs_from_snarkjs(&input_strings);
		assert!(result.is_ok());

		let inputs = result.unwrap();
		assert_eq!(inputs.len(), 0);
		assert!(inputs.is_empty());
	}

	#[test]
	fn test_parse_public_inputs_large_values() {
		// p - 1 is the largest canonical scalar; it must parse.
		let input_strings = [
			"1000000000000000000000",
			"21888242871839275222246405745257275088548364400416034343698204186575808495616",
		];
		let result = parse_public_inputs_from_snarkjs(&input_strings);
		assert!(result.is_ok(), "Should parse large valid values");

		let inputs = result.unwrap();
		assert_eq!(inputs.len(), 2);
	}

	#[test]
	fn test_parse_public_inputs_rejects_modulus() {
		// p itself (== 0 mod p) is non-canonical → rejected, not reduced.
		let result = parse_public_inputs_from_snarkjs(&[
			"21888242871839275222246405745257275088548364400416034343698204186575808495617",
		]);
		assert_eq!(result, Err(VerifierError::InvalidPublicInput));
	}

	#[test]
	fn test_parse_public_inputs_zero() {
		let input_strings = ["0"];
		let result = parse_public_inputs_from_snarkjs(&input_strings);
		assert!(result.is_ok());

		let inputs = result.unwrap();
		assert_eq!(inputs.len(), 1);
	}

	#[test]
	fn test_parse_public_inputs_many_inputs() {
		let input_strings: Vec<&str> = (0..32).map(|_| "123").collect();
		let result = parse_public_inputs_from_snarkjs(&input_strings);
		assert!(result.is_ok());

		let inputs = result.unwrap();
		assert_eq!(inputs.len(), 32);
	}

	#[test]
	fn test_parse_public_inputs_invalid_string() {
		let result = parse_public_inputs_from_snarkjs(&["not_a_number", "123"]);
		assert_eq!(result, Err(VerifierError::InvalidPublicInput));
	}

	#[test]
	fn test_parse_public_inputs_negative_number() {
		let result = parse_public_inputs_from_snarkjs(&["-123"]);
		assert_eq!(result, Err(VerifierError::InvalidPublicInput));
	}

	#[test]
	fn test_parse_public_inputs_hex_without_prefix() {
		let result = parse_public_inputs_from_snarkjs(&["0xabc123"]);
		assert_eq!(result, Err(VerifierError::InvalidPublicInput));
	}

	// === parse_proof_from_snarkjs Tests ===

	#[test]
	fn test_parse_proof_from_snarkjs_valid() {
		// Valid proof points from a real proof
		let proof_points = SnarkjsProofPoints {
			a_x: "19310665078306784406662215815651232366118953555532993625404293661707393313612",
			a_y: "11526666870423797426171768900087789746235310963851363013222396772078662171115",
			b_x0: "6010443894014200233438330038448044759571488627884631111958559202603979987992",
			b_x1: "19893187996136105803907318491959710717180097069680221139759473467891217377198",
			b_y0: "1793890726789761517579060243340680077348695067467741558973424433312717183077",
			b_y1: "8418746653214820419604605015564182122929427496727580773178512074941139353055",
			c_x: "19943346293308443045296477224123020528716829401937379717970359710082396275231",
			c_y: "17070758087329749108157075328504249625824445825715061802638610182418487497999",
		};

		let result = parse_proof_from_snarkjs(proof_points);
		assert!(result.is_ok(), "Should parse valid proof");

		let proof = result.unwrap();
		assert!(!proof.as_bytes().is_empty());
	}

	#[test]
	fn test_parse_proof_invalid_a_x() {
		let proof_points = SnarkjsProofPoints {
			a_x: "invalid",
			a_y: "11526666870423797426171768900087789746235310963851363013222396772078662171115",
			b_x0: "6010443894014200233438330038448044759571488627884631111958559202603979987992",
			b_x1: "19893187996136105803907318491959710717180097069680221139759473467891217377198",
			b_y0: "1793890726789761517579060243340680077348695067467741558973424433312717183077",
			b_y1: "8418746653214820419604605015564182122929427496727580773178512074941139353055",
			c_x: "19943346293308443045296477224123020528716829401937379717970359710082396275231",
			c_y: "17070758087329749108157075328504249625824445825715061802638610182418487497999",
		};

		assert_eq!(
			parse_proof_from_snarkjs(proof_points),
			Err(VerifierError::InvalidProof)
		);
	}

	#[test]
	fn test_parse_proof_invalid_b_coordinate() {
		let proof_points = SnarkjsProofPoints {
			a_x: "19310665078306784406662215815651232366118953555532993625404293661707393313612",
			a_y: "11526666870423797426171768900087789746235310963851363013222396772078662171115",
			b_x0: "invalid_coordinate",
			b_x1: "19893187996136105803907318491959710717180097069680221139759473467891217377198",
			b_y0: "1793890726789761517579060243340680077348695067467741558973424433312717183077",
			b_y1: "8418746653214820419604605015564182122929427496727580773178512074941139353055",
			c_x: "19943346293308443045296477224123020528716829401937379717970359710082396275231",
			c_y: "17070758087329749108157075328504249625824445825715061802638610182418487497999",
		};

		assert_eq!(
			parse_proof_from_snarkjs(proof_points),
			Err(VerifierError::InvalidProof)
		);
	}

	#[test]
	fn test_parse_proof_invalid_c_y() {
		let proof_points = SnarkjsProofPoints {
			a_x: "19310665078306784406662215815651232366118953555532993625404293661707393313612",
			a_y: "11526666870423797426171768900087789746235310963851363013222396772078662171115",
			b_x0: "6010443894014200233438330038448044759571488627884631111958559202603979987992",
			b_x1: "19893187996136105803907318491959710717180097069680221139759473467891217377198",
			b_y0: "1793890726789761517579060243340680077348695067467741558973424433312717183077",
			b_y1: "8418746653214820419604605015564182122929427496727580773178512074941139353055",
			c_x: "19943346293308443045296477224123020528716829401937379717970359710082396275231",
			c_y: "",
		};

		assert_eq!(
			parse_proof_from_snarkjs(proof_points),
			Err(VerifierError::InvalidProof)
		);
	}

	// === Helper Function Tests ===

	#[test]
	fn test_parse_fq_valid() {
		assert!(parse_fq("123").is_ok());
		assert!(parse_fq("0").is_ok());
		assert!(parse_fq(
			"21888242871839275222246405745257275088548364400416034343698204186575808495616"
		)
		.is_ok());
	}

	#[test]
	fn test_parse_fq_invalid() {
		assert_eq!(parse_fq("not_a_number"), Err(VerifierError::InvalidProof));
	}

	#[test]
	fn test_parse_fq_rejects_non_canonical() {
		// q (the Fq modulus) and q+1 are >= modulus → rejected, not reduced.
		let q = "21888242871839275222246405745257275088696311157297823662689037894645226208583";
		let q_plus_1 =
			"21888242871839275222246405745257275088696311157297823662689037894645226208584";
		assert_eq!(parse_fq(q), Err(VerifierError::InvalidProof));
		assert_eq!(parse_fq(q_plus_1), Err(VerifierError::InvalidProof));
		// q - 1 is the largest canonical base-field value → accepted.
		let q_minus_1 =
			"21888242871839275222246405745257275088696311157297823662689037894645226208582";
		assert!(parse_fq(q_minus_1).is_ok());
	}

	#[test]
	fn test_parse_fr_valid() {
		assert!(parse_fr("456").is_ok());
		assert!(parse_fr("0").is_ok());
	}

	#[test]
	fn test_parse_fr_invalid() {
		assert_eq!(
			parse_fr("invalid_input"),
			Err(VerifierError::InvalidPublicInput)
		);
	}

	// === SnarkjsProofPoints Structure Test ===

	#[test]
	fn test_snarkjs_proof_points_construction() {
		let points = SnarkjsProofPoints {
			a_x: "1",
			a_y: "2",
			b_x0: "3",
			b_x1: "4",
			b_y0: "5",
			b_y1: "6",
			c_x: "7",
			c_y: "8",
		};

		assert_eq!(points.a_x, "1");
		assert_eq!(points.a_y, "2");
		assert_eq!(points.b_x0, "3");
		assert_eq!(points.b_x1, "4");
		assert_eq!(points.b_y0, "5");
		assert_eq!(points.b_y1, "6");
		assert_eq!(points.c_x, "7");
		assert_eq!(points.c_y, "8");
	}
}
