
//! Autogenerated weights for pallet_zk_verifier
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.1
//! DATE: 2026-10-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-fsn1-1`, CPU: `AMD EPYC-Genoa Processor`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/orbinum-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_zk_verifier
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution=compiled
// --heap-pages=4096
// --default-pov-mode
// measured
// --no-median-slopes
// --output
// ./frame/zk-verifier/src/weights.rs
// --template
// ./scripts/benchmarks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_zk_verifier.
pub trait WeightInfo {
	fn verify_proof(n: u32, ) -> Weight;
	fn register_verification_key() -> Weight;
	fn set_active_version() -> Weight;
	fn remove_verification_key() -> Weight;
	fn retire_version() -> Weight;
	fn unretire_version() -> Weight;
	fn purge_circuit(v: u32, ) -> Weight;
	fn batch_register_verification_keys(n: u32, ) -> Weight;
}

/// Weights for pallet_zk_verifier using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:0)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:1 w:0)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `ZkVerifier::VerificationKeys` (r:1 w:0)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::VerificationStats` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationStats` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 16]`.
	fn verify_proof(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408 + n * (32 ±0)`
		//  Estimated: `3873 + n * (32 ±0)`
		// Minimum execution time: 10_147_056_000 picoseconds.
		Weight::from_parts(10_365_325_680, 3873)
			// Standard Error: 1_288_908
			.saturating_add(Weight::from_parts(49_605_680, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(n.into()))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:2 w:1)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:1)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `ZkVerifier::VkHashes` (r:0 w:1)
	/// Proof: `ZkVerifier::VkHashes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `Measured`)
	fn register_verification_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `6079`
		// Minimum execution time: 2_301_548_000 picoseconds.
		Weight::from_parts(2_357_859_000, 6079)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:1 w:0)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:1 w:0)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:0 w:1)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	fn set_active_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `194`
		//  Estimated: `3659`
		// Minimum execution time: 14_300_000 picoseconds.
		Weight::from_parts(15_100_000, 3659)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:0)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:0 w:1)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `ZkVerifier::VkHashes` (r:0 w:1)
	/// Proof: `ZkVerifier::VkHashes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `Measured`)
	/// Storage: `ZkVerifier::VerificationStats` (r:0 w:1)
	/// Proof: `ZkVerifier::VerificationStats` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `Measured`)
	fn remove_verification_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205`
		//  Estimated: `3670`
		// Minimum execution time: 20_690_000 picoseconds.
		Weight::from_parts(21_780_000, 3670)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:1 w:0)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:1 w:1)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:0)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn retire_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205`
		//  Estimated: `3670`
		// Minimum execution time: 17_640_000 picoseconds.
		Weight::from_parts(18_460_000, 3670)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ZkVerifier::RetiredVersions` (r:1 w:1)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn unretire_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `3624`
		// Minimum execution time: 12_830_000 picoseconds.
		Weight::from_parts(13_630_000, 3624)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:65 w:64)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::VkHashes` (r:65 w:64)
	/// Proof: `ZkVerifier::VkHashes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `Measured`)
	/// Storage: `ZkVerifier::VerificationStats` (r:65 w:64)
	/// Proof: `ZkVerifier::VerificationStats` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:65 w:64)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:1)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `v` is `[1, 64]`.
	fn purge_circuit(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `395 + v * (184 ±0)`
		//  Estimated: `3857 + v * (2660 ±0)`
		// Minimum execution time: 44_650_000 picoseconds.
		Weight::from_parts(45_331_764, 3857)
			// Standard Error: 8_950
			.saturating_add(Weight::from_parts(9_204_862, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((4_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 2660).saturating_mul(v.into()))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:20 w:10)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:0 w:10)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `ZkVerifier::VkHashes` (r:0 w:10)
	/// Proof: `ZkVerifier::VkHashes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `Measured`)
	/// The range of component `n` is `[1, 10]`.
	fn batch_register_verification_keys(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `1624 + n * (4950 ±0)`
		// Minimum execution time: 2_317_349_000 picoseconds.
		Weight::from_parts(55_663_312, 1624)
			// Standard Error: 1_723_849
			.saturating_add(Weight::from_parts(2_351_564_240, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 4950).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:0)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:1 w:0)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `ZkVerifier::VerificationKeys` (r:1 w:0)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::VerificationStats` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationStats` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 16]`.
	fn verify_proof(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408 + n * (32 ±0)`
		//  Estimated: `3873 + n * (32 ±0)`
		// Minimum execution time: 10_147_056_000 picoseconds.
		Weight::from_parts(10_365_325_680, 3873)
			// Standard Error: 1_288_908
			.saturating_add(Weight::from_parts(49_605_680, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(n.into()))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:2 w:1)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:1)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `ZkVerifier::VkHashes` (r:0 w:1)
	/// Proof: `ZkVerifier::VkHashes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `Measured`)
	fn register_verification_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `6079`
		// Minimum execution time: 2_301_548_000 picoseconds.
		Weight::from_parts(2_357_859_000, 6079)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:1 w:0)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:1 w:0)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:0 w:1)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	fn set_active_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `194`
		//  Estimated: `3659`
		// Minimum execution time: 14_300_000 picoseconds.
		Weight::from_parts(15_100_000, 3659)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:0)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:0 w:1)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `ZkVerifier::VkHashes` (r:0 w:1)
	/// Proof: `ZkVerifier::VkHashes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `Measured`)
	/// Storage: `ZkVerifier::VerificationStats` (r:0 w:1)
	/// Proof: `ZkVerifier::VerificationStats` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `Measured`)
	fn remove_verification_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205`
		//  Estimated: `3670`
		// Minimum execution time: 20_690_000 picoseconds.
		Weight::from_parts(21_780_000, 3670)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:1 w:0)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:1 w:1)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:0)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn retire_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205`
		//  Estimated: `3670`
		// Minimum execution time: 17_640_000 picoseconds.
		Weight::from_parts(18_460_000, 3670)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ZkVerifier::RetiredVersions` (r:1 w:1)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn unretire_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `3624`
		// Minimum execution time: 12_830_000 picoseconds.
		Weight::from_parts(13_630_000, 3624)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:65 w:64)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `ZkVerifier::VkHashes` (r:65 w:64)
	/// Proof: `ZkVerifier::VkHashes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `Measured`)
	/// Storage: `ZkVerifier::VerificationStats` (r:65 w:64)
	/// Proof: `ZkVerifier::VerificationStats` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `Measured`)
	/// Storage: `ZkVerifier::RetiredVersions` (r:65 w:64)
	/// Proof: `ZkVerifier::RetiredVersions` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:1 w:1)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `v` is `[1, 64]`.
	fn purge_circuit(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `395 + v * (184 ±0)`
		//  Estimated: `3857 + v * (2660 ±0)`
		// Minimum execution time: 44_650_000 picoseconds.
		Weight::from_parts(45_331_764, 3857)
			// Standard Error: 8_950
			.saturating_add(Weight::from_parts(9_204_862, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().reads((4_u64).saturating_mul(v.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((4_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 2660).saturating_mul(v.into()))
	}
	/// Storage: `ZkVerifier::VerificationKeys` (r:20 w:10)
	/// Proof: `ZkVerifier::VerificationKeys` (`max_values`: None, `max_size`: Some(8239), added: 10714, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ZkVerifier::ActiveCircuitVersion` (r:0 w:10)
	/// Proof: `ZkVerifier::ActiveCircuitVersion` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `Measured`)
	/// Storage: `ZkVerifier::VkHashes` (r:0 w:10)
	/// Proof: `ZkVerifier::VkHashes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `Measured`)
	/// The range of component `n` is `[1, 10]`.
	fn batch_register_verification_keys(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `1624 + n * (4950 ±0)`
		// Minimum execution time: 2_317_349_000 picoseconds.
		Weight::from_parts(55_663_312, 1624)
			// Standard Error: 1_723_849
			.saturating_add(Weight::from_parts(2_351_564_240, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 4950).saturating_mul(n.into()))
	}
}
