
//! Autogenerated weights for pallet_ismp
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-08-26, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBook-Air-de-Nolasco.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/orbinum-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_ismp
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=./template/runtime/src/weights/pallet_ismp.rs
// --template=./scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for pallet_ismp using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_ismp::weights::MigrationWeightInfo for SubstrateWeight<T> {
	/// Storage: `Ismp::StateCommitments` (r:999 w:999)
	/// Proof: `Ismp::StateCommitments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 1000]`.
	fn drain_state_commitments_step(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `105 + n * (70 ±0)`
		//  Estimated: `1114 + n * (2546 ±0)`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(468_845, 1114)
			// Standard Error: 1_599
			.saturating_add(Weight::from_parts(635_098, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2546).saturating_mul(n.into()))
	}
	/// Storage: `Ismp::StateMachineUpdateTime` (r:999 w:999)
	/// Proof: `Ismp::StateMachineUpdateTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 1000]`.
	fn drain_state_machine_update_time_step(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `143 + n * (37 ±0)`
		//  Estimated: `1127 + n * (2513 ±0)`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 1127)
			// Standard Error: 788
			.saturating_add(Weight::from_parts(641_750, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2513).saturating_mul(n.into()))
	}

	/// Storage: 500 child-trie keys under the `state` prefix (r:1 w:1 each).
	/// Proof: same keys. The benchmark CLI cannot name raw child-trie keys, so it
	/// emitted one `UNKNOWN KEY` pair per sampled key across the `[1, 500]` range.
	/// Collapsed here: the hashes are run artefacts, not part of the weight.
	/// The range of component `n` is `[1, 500]`.
	fn drain_child_trie_state_commitments_step(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `65 + n * (69 ±0)`
		//  Estimated: `19221 + n * (77 ±0)`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(3_000_000, 19221)
			// Standard Error: 4_024_965
			.saturating_add(Weight::from_parts(328_915_178, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 77).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests
