
//! Autogenerated weights for pallet_ismp_messaging
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.1
//! DATE: 2026-09-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-hel1-1`, CPU: `AMD EPYC-Genoa Processor`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

//! ## Hand-corrected value
//!
//! `dispatch_post`'s `proof_size` is set to **3550**, not the generator's output. The CLI
//! emitted `2585700789447993344` (~2.5 exabytes) against a measured 85 bytes: the call
//! reads ~50 `RequestCommitments` keys owned by `pallet-ismp`, which declares no
//! `MaxEncodedLen`, and `min_squares_iqr` writes its intercept without the `.max(0f64)`
//! clamp that `median_slopes` applies (`frame-benchmarking-49.0.0/src/analysis.rs:419`
//! vs `:338`). The value is not even deterministic — a second run produced
//! `8126544059662763008`.
//!
//! 3550 is what the same benchmark produces at `--steps 3`, where the analysis does not
//! blow up, and it sits inside this pallet's own range (1504-3606).
//!
//! **Regenerating this file will reintroduce the bad value.** Check `dispatch_post`'s
//! `proof_size` against the other extrinsics before committing. Reported upstream.

// Executed Command:
// ./target/release/orbinum-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_ismp_messaging
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./frame/ismp-messaging/src/weights.rs
// --template
// ./scripts/benchmarks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_ismp_messaging.
pub trait WeightInfo {
	fn dispatch_post(b: u32, ) -> Weight;
	fn accept_source() -> Weight;
	fn remove_source() -> Weight;
	fn on_accept(b: u32, ) -> Weight;
	fn on_response(n: u32, ) -> Weight;
	fn on_timeout() -> Weight;
}

/// Weights for pallet_ismp_messaging using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340b415c69721ad402b0506c2ef62` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340b415c69721ad402b0506c2ef62` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747393f9dbd9a78f06cf6e8e8e860db7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747393f9dbd9a78f06cf6e8e8e860db7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473abf1946ac92c8f2e9ec5906ad066` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473abf1946ac92c8f2e9ec5906ad066` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731353656cdfabdc5aa6bc0544161e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731353656cdfabdc5aa6bc0544161e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738383b0fbbe0fa35d7c535c7599e0` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738383b0fbbe0fa35d7c535c7599e0` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473adade17e7895b7e6fd9082ba929d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473adade17e7895b7e6fd9082ba929d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747317c707d78172f4879c466faa30af` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747317c707d78172f4879c466faa30af` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734e31fc2e43b80d3ba0bbf7ffea73` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734e31fc2e43b80d3ba0bbf7ffea73` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473291002e3d32a081a34a3653750ca` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473291002e3d32a081a34a3653750ca` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747339feb5ca6471019d4ea5e416265e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747339feb5ca6471019d4ea5e416265e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473794824d0588df97a0a6e0b3d6776` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473794824d0588df97a0a6e0b3d6776` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329f4bbe9281435b6311f1acca8dd` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329f4bbe9281435b6311f1acca8dd` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fe6105bbd1fb93c52ff89906157a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fe6105bbd1fb93c52ff89906157a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734370ed022c1b006e6890a3b40cec` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734370ed022c1b006e6890a3b40cec` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747324748d5a116a55441f32571ca436` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747324748d5a116a55441f32571ca436` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736edcf4b5633979f7a8d446d8ddca` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736edcf4b5633979f7a8d446d8ddca` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473034140013fef41fc27f40bb8d747` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473034140013fef41fc27f40bb8d747` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ab94b8310c7a3a4a8dd9a77694db` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ab94b8310c7a3a4a8dd9a77694db` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a218d81272539bf8365ea28f770c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a218d81272539bf8365ea28f770c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bf0495a31bfddbdd4a7d4459a819` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bf0495a31bfddbdd4a7d4459a819` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747325739de424ed136671de9a0022cf` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747325739de424ed136671de9a0022cf` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473818ce57c2a11ebd9d6c703329362` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473818ce57c2a11ebd9d6c703329362` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737f04aad49868ba48b6ff203adb38` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737f04aad49868ba48b6ff203adb38` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737c744d2476e2be814511a4cabf88` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737c744d2476e2be814511a4cabf88` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739a55e15e7ccc3207c6978116eae2` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739a55e15e7ccc3207c6978116eae2` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ca156bfec267e344580ae0fc8c5c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ca156bfec267e344580ae0fc8c5c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733383581e3bd63a1cfb21f98ac0c1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733383581e3bd63a1cfb21f98ac0c1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747367c106b2f4ecc5af717dea5b9266` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747367c106b2f4ecc5af717dea5b9266` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473054281ec6ccafdfe47a34514bcaa` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473054281ec6ccafdfe47a34514bcaa` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738533f91fefa4cfec618f1ef7d9bc` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738533f91fefa4cfec618f1ef7d9bc` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f7893c81d935a3f21f8853f5dc1a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f7893c81d935a3f21f8853f5dc1a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731ac7b1c6f0d8c23442f7bf55732f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731ac7b1c6f0d8c23442f7bf55732f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e594752207d205d8aff772d05f77` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e594752207d205d8aff772d05f77` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d4231557decfa394c458364c37f4` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d4231557decfa394c458364c37f4` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730e3266997638d854ecaa14e48dd8` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730e3266997638d854ecaa14e48dd8` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473316f78aefa1c6e61e0d9845ff923` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473316f78aefa1c6e61e0d9845ff923` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a1c78fe2f2f6d5adb3bcbd53f92c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a1c78fe2f2f6d5adb3bcbd53f92c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fd03480d6773e55a054f5cd1ffce` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fd03480d6773e55a054f5cd1ffce` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747383d5ef2d8baa9f8552e703e33d8f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747383d5ef2d8baa9f8552e703e33d8f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736dae095cff8137342acfc60d2c2a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736dae095cff8137342acfc60d2c2a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e040408e56aa000c7b4689451025` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e040408e56aa000c7b4689451025` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747358be6b74c3d28f0f592c68e8309a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747358be6b74c3d28f0f592c68e8309a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731638eca9844ab9e17c8f6770ea50` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731638eca9844ab9e17c8f6770ea50` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c4c7da7815f711a4df259b53a673` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c4c7da7815f711a4df259b53a673` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733b8782552053539c90f15b1ab426` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733b8782552053539c90f15b1ab426` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473afb30492728b7ded86d389d9b8e0` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473afb30492728b7ded86d389d9b8e0` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734bf9df4a428f7aeef0ed7c505670` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734bf9df4a428f7aeef0ed7c505670` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a32ea669af2d9aa09a9fff29f7bc` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a32ea669af2d9aa09a9fff29f7bc` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473032283e8a300be31b1e3ac5e04a1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473032283e8a300be31b1e3ac5e04a1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735ba74514b814405e606e9010e70f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735ba74514b814405e606e9010e70f` (r:1 w:1)
	/// The range of component `b` is `[0, 8192]`.
	fn dispatch_post(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85`
		//  Estimated: `3550 + b * (21 ±0)` (hand-corrected, see the header)
		// Minimum execution time: 28_610_000 picoseconds.
		Weight::from_parts(31_725_511, 3550)
			// Standard Error: 8
			.saturating_add(Weight::from_parts(6_400, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 21).saturating_mul(b.into()))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::AcceptedSources` (r:0 w:1)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn accept_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 8_590_000 picoseconds.
		Weight::from_parts(9_530_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::AcceptedSources` (r:0 w:1)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 8_640_000 picoseconds.
		Weight::from_parts(9_610_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `IsmpMessaging::AcceptedSources` (r:1 w:0)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::InboundCount` (r:1 w:1)
	/// Proof: `IsmpMessaging::InboundCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[0, 8192]`.
	fn on_accept(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `141`
		//  Estimated: `3606`
		// Minimum execution time: 10_790_000 picoseconds.
		Weight::from_parts(12_038_716, 3606)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(222, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 64]`.
	fn on_response(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 4_860_000 picoseconds.
		Weight::from_parts(5_424_193, 1504)
			// Standard Error: 49
			.saturating_add(Weight::from_parts(139_248, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn on_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 4_870_000 picoseconds.
		Weight::from_parts(5_400_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340b415c69721ad402b0506c2ef62` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340b415c69721ad402b0506c2ef62` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747393f9dbd9a78f06cf6e8e8e860db7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747393f9dbd9a78f06cf6e8e8e860db7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473abf1946ac92c8f2e9ec5906ad066` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473abf1946ac92c8f2e9ec5906ad066` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731353656cdfabdc5aa6bc0544161e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731353656cdfabdc5aa6bc0544161e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738383b0fbbe0fa35d7c535c7599e0` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738383b0fbbe0fa35d7c535c7599e0` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473adade17e7895b7e6fd9082ba929d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473adade17e7895b7e6fd9082ba929d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747317c707d78172f4879c466faa30af` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747317c707d78172f4879c466faa30af` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734e31fc2e43b80d3ba0bbf7ffea73` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734e31fc2e43b80d3ba0bbf7ffea73` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473291002e3d32a081a34a3653750ca` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473291002e3d32a081a34a3653750ca` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747339feb5ca6471019d4ea5e416265e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747339feb5ca6471019d4ea5e416265e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473794824d0588df97a0a6e0b3d6776` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473794824d0588df97a0a6e0b3d6776` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329f4bbe9281435b6311f1acca8dd` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329f4bbe9281435b6311f1acca8dd` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fe6105bbd1fb93c52ff89906157a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fe6105bbd1fb93c52ff89906157a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734370ed022c1b006e6890a3b40cec` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734370ed022c1b006e6890a3b40cec` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747324748d5a116a55441f32571ca436` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747324748d5a116a55441f32571ca436` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736edcf4b5633979f7a8d446d8ddca` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736edcf4b5633979f7a8d446d8ddca` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473034140013fef41fc27f40bb8d747` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473034140013fef41fc27f40bb8d747` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ab94b8310c7a3a4a8dd9a77694db` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ab94b8310c7a3a4a8dd9a77694db` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a218d81272539bf8365ea28f770c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a218d81272539bf8365ea28f770c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bf0495a31bfddbdd4a7d4459a819` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bf0495a31bfddbdd4a7d4459a819` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747325739de424ed136671de9a0022cf` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747325739de424ed136671de9a0022cf` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473818ce57c2a11ebd9d6c703329362` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473818ce57c2a11ebd9d6c703329362` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737f04aad49868ba48b6ff203adb38` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737f04aad49868ba48b6ff203adb38` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737c744d2476e2be814511a4cabf88` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737c744d2476e2be814511a4cabf88` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739a55e15e7ccc3207c6978116eae2` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739a55e15e7ccc3207c6978116eae2` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ca156bfec267e344580ae0fc8c5c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ca156bfec267e344580ae0fc8c5c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733383581e3bd63a1cfb21f98ac0c1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733383581e3bd63a1cfb21f98ac0c1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747367c106b2f4ecc5af717dea5b9266` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747367c106b2f4ecc5af717dea5b9266` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473054281ec6ccafdfe47a34514bcaa` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473054281ec6ccafdfe47a34514bcaa` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738533f91fefa4cfec618f1ef7d9bc` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738533f91fefa4cfec618f1ef7d9bc` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f7893c81d935a3f21f8853f5dc1a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f7893c81d935a3f21f8853f5dc1a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731ac7b1c6f0d8c23442f7bf55732f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731ac7b1c6f0d8c23442f7bf55732f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e594752207d205d8aff772d05f77` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e594752207d205d8aff772d05f77` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d4231557decfa394c458364c37f4` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d4231557decfa394c458364c37f4` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730e3266997638d854ecaa14e48dd8` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730e3266997638d854ecaa14e48dd8` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473316f78aefa1c6e61e0d9845ff923` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473316f78aefa1c6e61e0d9845ff923` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a1c78fe2f2f6d5adb3bcbd53f92c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a1c78fe2f2f6d5adb3bcbd53f92c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fd03480d6773e55a054f5cd1ffce` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fd03480d6773e55a054f5cd1ffce` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747383d5ef2d8baa9f8552e703e33d8f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747383d5ef2d8baa9f8552e703e33d8f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736dae095cff8137342acfc60d2c2a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736dae095cff8137342acfc60d2c2a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e040408e56aa000c7b4689451025` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e040408e56aa000c7b4689451025` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747358be6b74c3d28f0f592c68e8309a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747358be6b74c3d28f0f592c68e8309a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731638eca9844ab9e17c8f6770ea50` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731638eca9844ab9e17c8f6770ea50` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c4c7da7815f711a4df259b53a673` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c4c7da7815f711a4df259b53a673` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733b8782552053539c90f15b1ab426` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733b8782552053539c90f15b1ab426` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473afb30492728b7ded86d389d9b8e0` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473afb30492728b7ded86d389d9b8e0` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734bf9df4a428f7aeef0ed7c505670` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734bf9df4a428f7aeef0ed7c505670` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a32ea669af2d9aa09a9fff29f7bc` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a32ea669af2d9aa09a9fff29f7bc` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473032283e8a300be31b1e3ac5e04a1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473032283e8a300be31b1e3ac5e04a1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735ba74514b814405e606e9010e70f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735ba74514b814405e606e9010e70f` (r:1 w:1)
	/// The range of component `b` is `[0, 8192]`.
	fn dispatch_post(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85`
		//  Estimated: `3550 + b * (21 ±0)` (hand-corrected, see the header)
		// Minimum execution time: 28_610_000 picoseconds.
		Weight::from_parts(31_725_511, 3550)
			// Standard Error: 8
			.saturating_add(Weight::from_parts(6_400, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 21).saturating_mul(b.into()))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::AcceptedSources` (r:0 w:1)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn accept_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 8_590_000 picoseconds.
		Weight::from_parts(9_530_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::AcceptedSources` (r:0 w:1)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 8_640_000 picoseconds.
		Weight::from_parts(9_610_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `IsmpMessaging::AcceptedSources` (r:1 w:0)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::InboundCount` (r:1 w:1)
	/// Proof: `IsmpMessaging::InboundCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[0, 8192]`.
	fn on_accept(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `141`
		//  Estimated: `3606`
		// Minimum execution time: 10_790_000 picoseconds.
		Weight::from_parts(12_038_716, 3606)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(222, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 64]`.
	fn on_response(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 4_860_000 picoseconds.
		Weight::from_parts(5_424_193, 1504)
			// Standard Error: 49
			.saturating_add(Weight::from_parts(139_248, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn on_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 4_870_000 picoseconds.
		Weight::from_parts(5_400_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
