
//! Autogenerated weights for pallet_ismp_messaging
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.1
//! DATE: 2026-10-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-fsn1-1`, CPU: `AMD EPYC-Genoa Processor`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024
//! ## Hand-corrected value
//!
//! `dispatch_get`'s base `proof_size` is set to **3748**, not the generator's output.
//! The CLI emitted `8433417681689641984` (~8 exabytes) against a measured 283 bytes. The
//! bug is not deterministic and hits a different extrinsic from run to run: the
//! previous regeneration corrupted `dispatch_post` instead (`2585700789447993344`).
//!
//! Cause, per the upstream fix: these calls read `RequestCommitments` keys owned by
//! `pallet-ismp`, which declares no `MaxEncodedLen`, so they land in the analysis as
//! `UNKNOWN KEY`. `min_squares_iqr` runs per storage prefix, and a prefix observed at
//! only one component value makes the OLS design matrix rank-deficient; `linregress`'s
//! pseudo-inverse then returns an intercept in the 10^18 range.
//!
//! 3748 is what the same benchmark produces at `--steps 3` and `--steps 5` (proof size is
//! measured storage, so it does not depend on the host), and it equals `dispatch_post`'s
//! base on this run, which walks the same `RequestCommitments` path. The per-key slope
//! (`k * 1874`) was not affected and is the generator's.
//!
//! **Regenerating this file with an unfixed CLI can reintroduce a bad value.**
//! `tests::declared_proof_sizes_stay_within_a_sane_ceiling` fails on it; check every
//! extrinsic's `proof_size` before committing.
//!
//! Reported as paritytech/polkadot-sdk#13066; fix proposed in PR #13073. It targets
//! `master`, while `pallet-ismp` pins us to `polkadot-sdk =2606.0.0`, so this note stands
//! until we move SDK lines. Then drop it and regenerate.

// Executed Command:
// ./target/release/orbinum-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_ismp_messaging
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution=compiled
// --heap-pages=4096
// --default-pov-mode
// measured
// --no-median-slopes
// --output
// ./frame/ismp-messaging/src/weights.rs
// --template
// ./scripts/benchmarks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_ismp_messaging.
pub trait WeightInfo {
	fn dispatch_post(b: u32, ) -> Weight;
	fn dispatch_get(k: u32, ) -> Weight;
	fn accept_source() -> Weight;
	fn remove_source() -> Weight;
	fn set_message_fee() -> Weight;
	fn set_outbound_paused() -> Weight;
	fn on_accept(b: u32, ) -> Weight;
	fn on_response(n: u32, ) -> Weight;
	fn on_timeout() -> Weight;
}

/// Weights for pallet_ismp_messaging using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `IsmpMessaging::OutboundPaused` (r:1 w:0)
	/// Proof: `IsmpMessaging::OutboundPaused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageFee` (r:1 w:0)
	/// Proof: `IsmpMessaging::MessageFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageByteFee` (r:1 w:0)
	/// Proof: `IsmpMessaging::MessageByteFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735a09a1f31df49ac6f2c41354510d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735a09a1f31df49ac6f2c41354510d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473706e70d18847040faaf0f487aa64` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473706e70d18847040faaf0f487aa64` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736889bb72d704e38ceb1457c1ac79` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736889bb72d704e38ceb1457c1ac79` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731d991f99551101d691d4059bcd4b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731d991f99551101d691d4059bcd4b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473400f5e036deb475d4feaf3542adf` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473400f5e036deb475d4feaf3542adf` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d78230e639836bb230ffda67918c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d78230e639836bb230ffda67918c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734490ed3f44b883fc51bb62c7727c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734490ed3f44b883fc51bb62c7727c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ff0307692ea77209400bda387123` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ff0307692ea77209400bda387123` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735f58803e856fba374d46c87cec7b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735f58803e856fba374d46c87cec7b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329baf3be1bf9cceb304843c6a6ac` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329baf3be1bf9cceb304843c6a6ac` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747351e67b0d3c9f53457b7d839962e9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747351e67b0d3c9f53457b7d839962e9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e244377f7449ddaf2fd6e069900f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e244377f7449ddaf2fd6e069900f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a8c4348092f06892fe9a058d85b4` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a8c4348092f06892fe9a058d85b4` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473656cb9eadd58dc51f32dd02f15ed` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473656cb9eadd58dc51f32dd02f15ed` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ea26dfc971864a62379a50b3f0a1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ea26dfc971864a62379a50b3f0a1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d0314b9ee9641960cc3b05fd007e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d0314b9ee9641960cc3b05fd007e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747344b6cfe9dbb0575793a9f968859f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747344b6cfe9dbb0575793a9f968859f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ab22f338be131924e826b1ea5ae7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ab22f338be131924e826b1ea5ae7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473db8e8a4f8b72d0bf5ff0e1ed0a4e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473db8e8a4f8b72d0bf5ff0e1ed0a4e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735b5dccf4647c70c3071506a5741a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735b5dccf4647c70c3071506a5741a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ebdfe4d082bdf8248896aa349a87` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ebdfe4d082bdf8248896aa349a87` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473971914eed4149c3b2cc13892aaa9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473971914eed4149c3b2cc13892aaa9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738998ac946a0c36814289f87b7e8d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738998ac946a0c36814289f87b7e8d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473286b4c4e2398d688fc42b5ca723b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473286b4c4e2398d688fc42b5ca723b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734593a330b4a3b3cb3182b8faeecb` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734593a330b4a3b3cb3182b8faeecb` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473929cb537afa728fab50f928f37db` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473929cb537afa728fab50f928f37db` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731b624653a32d3ee0e2bc2786624c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731b624653a32d3ee0e2bc2786624c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d8bc8791bc8be4f1c385c6bfb21e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d8bc8791bc8be4f1c385c6bfb21e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747354bd20a830d162c29de4e67bea43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747354bd20a830d162c29de4e67bea43` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b8488f705a439aa4297bdbde2972` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b8488f705a439aa4297bdbde2972` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cfe216ff496a7b3a97eaf77e12f5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cfe216ff496a7b3a97eaf77e12f5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f21a244545caa85bca31b5e2e830` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f21a244545caa85bca31b5e2e830` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735fa447b7893fda24f6091e1f91a5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735fa447b7893fda24f6091e1f91a5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747380b17dfaa24903e7a9dba869ce05` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747380b17dfaa24903e7a9dba869ce05` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738388c58fcbaa6c489508aa06417d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738388c58fcbaa6c489508aa06417d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730143291a60c9c57c42fff09bfe05` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730143291a60c9c57c42fff09bfe05` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ac95051b0d2d6cacd5865cd45769` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ac95051b0d2d6cacd5865cd45769` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473165dd52dc00d3fe610b68c4d7d8b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473165dd52dc00d3fe610b68c4d7d8b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737356fda81886c6ed2edfcb8a0301` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737356fda81886c6ed2edfcb8a0301` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736694413ab0509901ef97bb2dc781` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736694413ab0509901ef97bb2dc781` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735e5dd21168124b18a65c368d7fcf` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735e5dd21168124b18a65c368d7fcf` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732d7151fceccba145a2d0a3e078a1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732d7151fceccba145a2d0a3e078a1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c37a9983a88f79bb93d409ef0ece` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c37a9983a88f79bb93d409ef0ece` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473565827ac303e178d5ceec5a6922c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473565827ac303e178d5ceec5a6922c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739e21cbbd87d65d2af793cd57aa89` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739e21cbbd87d65d2af793cd57aa89` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e6f7989dce3480f4b894ed22f610` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e6f7989dce3480f4b894ed22f610` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340dfbece91f8af6c8e1c99037413` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340dfbece91f8af6c8e1c99037413` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e5265b113afa9c7d20dbbcfff25c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e5265b113afa9c7d20dbbcfff25c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739fb285e20751aa43cc3883b465ff` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739fb285e20751aa43cc3883b465ff` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747337ebdbd6df85e514de9d7769d3b0` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747337ebdbd6df85e514de9d7769d3b0` (r:1 w:1)
	/// The range of component `b` is `[0, 8192]`.
	fn dispatch_post(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3748 + b * (22 ±0)`
		// Minimum execution time: 86_130_000 picoseconds.
		Weight::from_parts(93_759_112, 3748)
			// Standard Error: 13
			.saturating_add(Weight::from_parts(5_067, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 22).saturating_mul(b.into()))
	}
	/// Storage: `IsmpMessaging::OutboundPaused` (r:1 w:0)
	/// Proof: `IsmpMessaging::OutboundPaused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageFee` (r:1 w:0)
	/// Proof: `IsmpMessaging::MessageFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageByteFee` (r:1 w:0)
	/// Proof: `IsmpMessaging::MessageByteFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d6736d8e1494109128cdd1572cc9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d6736d8e1494109128cdd1572cc9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ed3044caae7e609229244d7db4db` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ed3044caae7e609229244d7db4db` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ca82e811a5f658474b24be5680ae` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ca82e811a5f658474b24be5680ae` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735cab3f44c434df0ce97dce33f0c7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735cab3f44c434df0ce97dce33f0c7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730421fbb10bd09ddc394fe5536876` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730421fbb10bd09ddc394fe5536876` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cd8cfb0743fe4c899958ddbc2496` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cd8cfb0743fe4c899958ddbc2496` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747338069d62b1fbc14e2117ceb4f741` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747338069d62b1fbc14e2117ceb4f741` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747395449d9f71e01595553007e8c4b8` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747395449d9f71e01595553007e8c4b8` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733286cb6c053e4a5344113a328e34` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733286cb6c053e4a5344113a328e34` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747378346c8ffc9025d7d65b1d86df79` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747378346c8ffc9025d7d65b1d86df79` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ce1f46b32e6432b8e29a7638d3da` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ce1f46b32e6432b8e29a7638d3da` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738696aa407d64f77ba5ca8cc580a4` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738696aa407d64f77ba5ca8cc580a4` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e86bab742a51bec2f6b649161565` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e86bab742a51bec2f6b649161565` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473909e70d515a7bbd18cb7929f475d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473909e70d515a7bbd18cb7929f475d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c89b9b6cf87ece54fd41e32b4440` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c89b9b6cf87ece54fd41e32b4440` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747347e9d72ca23733a68e86d13712be` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747347e9d72ca23733a68e86d13712be` (r:1 w:1)
	/// The range of component `k` is `[1, 16]`.
	fn dispatch_get(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3748 + k * (1874 ±0)`
		// Minimum execution time: 88_190_000 picoseconds.
		Weight::from_parts(94_419_325, 3748)
			// Standard Error: 6_520
			.saturating_add(Weight::from_parts(1_451_029, 0).saturating_mul(k.into()))
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 1874).saturating_mul(k.into()))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::AcceptedSources` (r:0 w:1)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn accept_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 7_740_000 picoseconds.
		Weight::from_parts(8_240_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::AcceptedSources` (r:0 w:1)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 7_720_000 picoseconds.
		Weight::from_parts(8_220_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageFee` (r:0 w:1)
	/// Proof: `IsmpMessaging::MessageFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageByteFee` (r:0 w:1)
	/// Proof: `IsmpMessaging::MessageByteFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_message_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 6_810_000 picoseconds.
		Weight::from_parts(7_320_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::OutboundPaused` (r:0 w:1)
	/// Proof: `IsmpMessaging::OutboundPaused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_outbound_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 6_410_000 picoseconds.
		Weight::from_parts(6_910_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `IsmpMessaging::AcceptedSources` (r:1 w:0)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::InboundCount` (r:1 w:1)
	/// Proof: `IsmpMessaging::InboundCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[0, 8192]`.
	fn on_accept(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `141`
		//  Estimated: `3606`
		// Minimum execution time: 14_110_000 picoseconds.
		Weight::from_parts(15_291_508, 3606)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(2_525, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 16]`.
	fn on_response(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 8_600_000 picoseconds.
		Weight::from_parts(10_879_469, 1504)
			// Standard Error: 689
			.saturating_add(Weight::from_parts(175_957, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn on_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 27_030_000 picoseconds.
		Weight::from_parts(27_720_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `IsmpMessaging::OutboundPaused` (r:1 w:0)
	/// Proof: `IsmpMessaging::OutboundPaused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageFee` (r:1 w:0)
	/// Proof: `IsmpMessaging::MessageFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageByteFee` (r:1 w:0)
	/// Proof: `IsmpMessaging::MessageByteFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735a09a1f31df49ac6f2c41354510d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735a09a1f31df49ac6f2c41354510d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473706e70d18847040faaf0f487aa64` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473706e70d18847040faaf0f487aa64` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736889bb72d704e38ceb1457c1ac79` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736889bb72d704e38ceb1457c1ac79` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731d991f99551101d691d4059bcd4b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731d991f99551101d691d4059bcd4b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473400f5e036deb475d4feaf3542adf` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473400f5e036deb475d4feaf3542adf` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d78230e639836bb230ffda67918c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d78230e639836bb230ffda67918c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734490ed3f44b883fc51bb62c7727c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734490ed3f44b883fc51bb62c7727c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ff0307692ea77209400bda387123` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ff0307692ea77209400bda387123` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735f58803e856fba374d46c87cec7b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735f58803e856fba374d46c87cec7b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329baf3be1bf9cceb304843c6a6ac` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329baf3be1bf9cceb304843c6a6ac` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747351e67b0d3c9f53457b7d839962e9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747351e67b0d3c9f53457b7d839962e9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e244377f7449ddaf2fd6e069900f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e244377f7449ddaf2fd6e069900f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a8c4348092f06892fe9a058d85b4` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a8c4348092f06892fe9a058d85b4` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473656cb9eadd58dc51f32dd02f15ed` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473656cb9eadd58dc51f32dd02f15ed` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ea26dfc971864a62379a50b3f0a1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ea26dfc971864a62379a50b3f0a1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d0314b9ee9641960cc3b05fd007e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d0314b9ee9641960cc3b05fd007e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747344b6cfe9dbb0575793a9f968859f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747344b6cfe9dbb0575793a9f968859f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ab22f338be131924e826b1ea5ae7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ab22f338be131924e826b1ea5ae7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473db8e8a4f8b72d0bf5ff0e1ed0a4e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473db8e8a4f8b72d0bf5ff0e1ed0a4e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735b5dccf4647c70c3071506a5741a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735b5dccf4647c70c3071506a5741a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ebdfe4d082bdf8248896aa349a87` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ebdfe4d082bdf8248896aa349a87` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473971914eed4149c3b2cc13892aaa9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473971914eed4149c3b2cc13892aaa9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738998ac946a0c36814289f87b7e8d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738998ac946a0c36814289f87b7e8d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473286b4c4e2398d688fc42b5ca723b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473286b4c4e2398d688fc42b5ca723b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734593a330b4a3b3cb3182b8faeecb` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734593a330b4a3b3cb3182b8faeecb` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473929cb537afa728fab50f928f37db` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473929cb537afa728fab50f928f37db` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731b624653a32d3ee0e2bc2786624c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731b624653a32d3ee0e2bc2786624c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d8bc8791bc8be4f1c385c6bfb21e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d8bc8791bc8be4f1c385c6bfb21e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747354bd20a830d162c29de4e67bea43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747354bd20a830d162c29de4e67bea43` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b8488f705a439aa4297bdbde2972` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b8488f705a439aa4297bdbde2972` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cfe216ff496a7b3a97eaf77e12f5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cfe216ff496a7b3a97eaf77e12f5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f21a244545caa85bca31b5e2e830` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f21a244545caa85bca31b5e2e830` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735fa447b7893fda24f6091e1f91a5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735fa447b7893fda24f6091e1f91a5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747380b17dfaa24903e7a9dba869ce05` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747380b17dfaa24903e7a9dba869ce05` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738388c58fcbaa6c489508aa06417d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738388c58fcbaa6c489508aa06417d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730143291a60c9c57c42fff09bfe05` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730143291a60c9c57c42fff09bfe05` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ac95051b0d2d6cacd5865cd45769` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ac95051b0d2d6cacd5865cd45769` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473165dd52dc00d3fe610b68c4d7d8b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473165dd52dc00d3fe610b68c4d7d8b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737356fda81886c6ed2edfcb8a0301` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737356fda81886c6ed2edfcb8a0301` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736694413ab0509901ef97bb2dc781` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736694413ab0509901ef97bb2dc781` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735e5dd21168124b18a65c368d7fcf` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735e5dd21168124b18a65c368d7fcf` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732d7151fceccba145a2d0a3e078a1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732d7151fceccba145a2d0a3e078a1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c37a9983a88f79bb93d409ef0ece` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c37a9983a88f79bb93d409ef0ece` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473565827ac303e178d5ceec5a6922c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473565827ac303e178d5ceec5a6922c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739e21cbbd87d65d2af793cd57aa89` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739e21cbbd87d65d2af793cd57aa89` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e6f7989dce3480f4b894ed22f610` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e6f7989dce3480f4b894ed22f610` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340dfbece91f8af6c8e1c99037413` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340dfbece91f8af6c8e1c99037413` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e5265b113afa9c7d20dbbcfff25c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e5265b113afa9c7d20dbbcfff25c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739fb285e20751aa43cc3883b465ff` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739fb285e20751aa43cc3883b465ff` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747337ebdbd6df85e514de9d7769d3b0` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747337ebdbd6df85e514de9d7769d3b0` (r:1 w:1)
	/// The range of component `b` is `[0, 8192]`.
	fn dispatch_post(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3748 + b * (22 ±0)`
		// Minimum execution time: 86_130_000 picoseconds.
		Weight::from_parts(93_759_112, 3748)
			// Standard Error: 13
			.saturating_add(Weight::from_parts(5_067, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 22).saturating_mul(b.into()))
	}
	/// Storage: `IsmpMessaging::OutboundPaused` (r:1 w:0)
	/// Proof: `IsmpMessaging::OutboundPaused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageFee` (r:1 w:0)
	/// Proof: `IsmpMessaging::MessageFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageByteFee` (r:1 w:0)
	/// Proof: `IsmpMessaging::MessageByteFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d6736d8e1494109128cdd1572cc9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d6736d8e1494109128cdd1572cc9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ed3044caae7e609229244d7db4db` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ed3044caae7e609229244d7db4db` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ca82e811a5f658474b24be5680ae` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ca82e811a5f658474b24be5680ae` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735cab3f44c434df0ce97dce33f0c7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735cab3f44c434df0ce97dce33f0c7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730421fbb10bd09ddc394fe5536876` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730421fbb10bd09ddc394fe5536876` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cd8cfb0743fe4c899958ddbc2496` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cd8cfb0743fe4c899958ddbc2496` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747338069d62b1fbc14e2117ceb4f741` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747338069d62b1fbc14e2117ceb4f741` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747395449d9f71e01595553007e8c4b8` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747395449d9f71e01595553007e8c4b8` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733286cb6c053e4a5344113a328e34` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733286cb6c053e4a5344113a328e34` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747378346c8ffc9025d7d65b1d86df79` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747378346c8ffc9025d7d65b1d86df79` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ce1f46b32e6432b8e29a7638d3da` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ce1f46b32e6432b8e29a7638d3da` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738696aa407d64f77ba5ca8cc580a4` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738696aa407d64f77ba5ca8cc580a4` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e86bab742a51bec2f6b649161565` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e86bab742a51bec2f6b649161565` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473909e70d515a7bbd18cb7929f475d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473909e70d515a7bbd18cb7929f475d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c89b9b6cf87ece54fd41e32b4440` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c89b9b6cf87ece54fd41e32b4440` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747347e9d72ca23733a68e86d13712be` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747347e9d72ca23733a68e86d13712be` (r:1 w:1)
	/// The range of component `k` is `[1, 16]`.
	fn dispatch_get(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3748 + k * (1874 ±0)`
		// Minimum execution time: 88_190_000 picoseconds.
		Weight::from_parts(94_419_325, 3748)
			// Standard Error: 6_520
			.saturating_add(Weight::from_parts(1_451_029, 0).saturating_mul(k.into()))
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 1874).saturating_mul(k.into()))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::AcceptedSources` (r:0 w:1)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn accept_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 7_740_000 picoseconds.
		Weight::from_parts(8_240_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::AcceptedSources` (r:0 w:1)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 7_720_000 picoseconds.
		Weight::from_parts(8_220_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageFee` (r:0 w:1)
	/// Proof: `IsmpMessaging::MessageFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::MessageByteFee` (r:0 w:1)
	/// Proof: `IsmpMessaging::MessageByteFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_message_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 6_810_000 picoseconds.
		Weight::from_parts(7_320_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::OutboundPaused` (r:0 w:1)
	/// Proof: `IsmpMessaging::OutboundPaused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_outbound_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 6_410_000 picoseconds.
		Weight::from_parts(6_910_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `IsmpMessaging::AcceptedSources` (r:1 w:0)
	/// Proof: `IsmpMessaging::AcceptedSources` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IsmpMessaging::InboundCount` (r:1 w:1)
	/// Proof: `IsmpMessaging::InboundCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[0, 8192]`.
	fn on_accept(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `141`
		//  Estimated: `3606`
		// Minimum execution time: 14_110_000 picoseconds.
		Weight::from_parts(15_291_508, 3606)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(2_525, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 16]`.
	fn on_response(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 8_600_000 picoseconds.
		Weight::from_parts(10_879_469, 1504)
			// Standard Error: 689
			.saturating_add(Weight::from_parts(175_957, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn on_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 27_030_000 picoseconds.
		Weight::from_parts(27_720_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
