
//! Autogenerated weights for pallet_relayer
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.1
//! DATE: 2026-10-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-fsn1-1`, CPU: `AMD EPYC-Genoa Processor`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/orbinum-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_relayer
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution=compiled
// --heap-pages=4096
// --default-pov-mode
// measured
// --no-median-slopes
// --output
// ./frame/relayer/src/weights.rs
// --template
// ./scripts/benchmarks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_relayer.
pub trait WeightInfo {
	fn set_min_relay_fee() -> Weight;
	fn set_allowed_selectors(n: u32, ) -> Weight;
	fn register_relayer() -> Weight;
	fn unregister_relayer() -> Weight;
	fn prune_relay_commits(r: u32, n: u32, ) -> Weight;
}

/// Weights for pallet_relayer using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::MinRelayFee` (r:0 w:1)
	/// Proof: `Relayer::MinRelayFee` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `Measured`)
	fn set_min_relay_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 6_310_000 picoseconds.
		Weight::from_parts(6_820_000, 1504)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::AllowedSelectors` (r:0 w:1)
	/// Proof: `Relayer::AllowedSelectors` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `Measured`)
	/// The range of component `n` is `[0, 16]`.
	fn set_allowed_selectors(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 6_570_000 picoseconds.
		Weight::from_parts(7_120_033, 1504)
			// Standard Error: 97
			.saturating_add(Weight::from_parts(5_956, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ValidatorSet::ApprovedValidators` (r:1 w:0)
	/// Proof: `ValidatorSet::ApprovedValidators` (`max_values`: Some(1), `max_size`: Some(1025), added: 1520, mode: `Measured`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `Measured`)
	/// Storage: `Relayer::RelayerRegistry` (r:1 w:1)
	/// Proof: `Relayer::RelayerRegistry` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `Measured`)
	/// Storage: `Relayer::RelayerByAccount` (r:1 w:1)
	/// Proof: `Relayer::RelayerByAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_relayer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3748`
		// Minimum execution time: 57_060_000 picoseconds.
		Weight::from_parts(59_120_000, 3748)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Relayer::RelayerByAccount` (r:1 w:1)
	/// Proof: `Relayer::RelayerByAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::RelayerRegistry` (r:0 w:1)
	/// Proof: `Relayer::RelayerRegistry` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `Measured`)
	fn unregister_relayer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3688`
		// Minimum execution time: 13_280_000 picoseconds.
		Weight::from_parts(14_110_000, 3688)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Relayer::CommitsByRelayer` (r:33 w:32)
	/// Proof: `Relayer::CommitsByRelayer` (`max_values`: None, `max_size`: Some(2110), added: 4585, mode: `Measured`)
	/// Storage: `Relayer::RelayCommits` (r:2048 w:2048)
	/// Proof: `Relayer::RelayCommits` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `Measured`)
	/// The range of component `r` is `[0, 32]`.
	/// The range of component `n` is `[0, 2048]`.
	fn prune_relay_commits(r: u32, n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (93 ±0) + r * (4652 ±0)`
		//  Estimated: `108330 + n * (852 ±3) + r * (59076 ±208)`
		// Minimum execution time: 131_250_000 picoseconds.
		Weight::from_parts(134_830_000, 108330)
			// Standard Error: 4_742_414
			.saturating_add(Weight::from_parts(154_221_135, 0).saturating_mul(r.into()))
			// Standard Error: 73_715
			.saturating_add(Weight::from_parts(2_195_591, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(33_u64))
			.saturating_add(T::DbWeight::get().reads((24_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(32_u64))
			.saturating_add(T::DbWeight::get().writes((24_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 852).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 59076).saturating_mul(r.into()))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::MinRelayFee` (r:0 w:1)
	/// Proof: `Relayer::MinRelayFee` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `Measured`)
	fn set_min_relay_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 6_310_000 picoseconds.
		Weight::from_parts(6_820_000, 1504)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::AllowedSelectors` (r:0 w:1)
	/// Proof: `Relayer::AllowedSelectors` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `Measured`)
	/// The range of component `n` is `[0, 16]`.
	fn set_allowed_selectors(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19`
		//  Estimated: `1504`
		// Minimum execution time: 6_570_000 picoseconds.
		Weight::from_parts(7_120_033, 1504)
			// Standard Error: 97
			.saturating_add(Weight::from_parts(5_956, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ValidatorSet::ApprovedValidators` (r:1 w:0)
	/// Proof: `ValidatorSet::ApprovedValidators` (`max_values`: Some(1), `max_size`: Some(1025), added: 1520, mode: `Measured`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `Measured`)
	/// Storage: `Relayer::RelayerRegistry` (r:1 w:1)
	/// Proof: `Relayer::RelayerRegistry` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `Measured`)
	/// Storage: `Relayer::RelayerByAccount` (r:1 w:1)
	/// Proof: `Relayer::RelayerByAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_relayer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3748`
		// Minimum execution time: 57_060_000 picoseconds.
		Weight::from_parts(59_120_000, 3748)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Relayer::RelayerByAccount` (r:1 w:1)
	/// Proof: `Relayer::RelayerByAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `Measured`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Relayer::RelayerRegistry` (r:0 w:1)
	/// Proof: `Relayer::RelayerRegistry` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `Measured`)
	fn unregister_relayer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3688`
		// Minimum execution time: 13_280_000 picoseconds.
		Weight::from_parts(14_110_000, 3688)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Relayer::CommitsByRelayer` (r:33 w:32)
	/// Proof: `Relayer::CommitsByRelayer` (`max_values`: None, `max_size`: Some(2110), added: 4585, mode: `Measured`)
	/// Storage: `Relayer::RelayCommits` (r:2048 w:2048)
	/// Proof: `Relayer::RelayCommits` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `Measured`)
	/// The range of component `r` is `[0, 32]`.
	/// The range of component `n` is `[0, 2048]`.
	fn prune_relay_commits(r: u32, n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (93 ±0) + r * (4652 ±0)`
		//  Estimated: `108330 + n * (852 ±3) + r * (59076 ±208)`
		// Minimum execution time: 131_250_000 picoseconds.
		Weight::from_parts(134_830_000, 108330)
			// Standard Error: 4_742_414
			.saturating_add(Weight::from_parts(154_221_135, 0).saturating_mul(r.into()))
			// Standard Error: 73_715
			.saturating_add(Weight::from_parts(2_195_591, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(33_u64))
			.saturating_add(RocksDbWeight::get().reads((24_u64).saturating_mul(r.into())))
			.saturating_add(RocksDbWeight::get().writes(32_u64))
			.saturating_add(RocksDbWeight::get().writes((24_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 852).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 59076).saturating_mul(r.into()))
	}
}
