
//! Autogenerated weights for `pallet_validator_set`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! Regenerate with:
//! ```bash
//! cargo build --release --features runtime-benchmarks
//! ./target/release/orbinum-node benchmark pallet \
//!   --chain=dev \
//!   --pallet=pallet_validator_set \
//!   --extrinsic='*' \
//!   --steps=50 \
//!   --repeat=20 \
//!   --output=frame/validator-set/src/weights.rs \
//!   --template=./scripts/frame-weight-template.hbs
//! ```

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_validator_set`.
pub trait WeightInfo {
	fn add_validator() -> Weight;
	fn remove_validator() -> Weight;
}

/// Weights for `pallet_validator_set` using the Substrate node and recommended hardware.
///
/// These are **conservative estimates** based on the storage layout (one
/// `BoundedVec` read-modify-write + one event deposit). Replace with
/// measured values after running `benchmark pallet` on target hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ValidatorSet::ApprovedValidators` (r:1 w:1)
	/// Proof: `ValidatorSet::ApprovedValidators` (`max_values`: Some(1), `max_size`: Some(1602), added: 2097, mode: `MaxEncodedLen`)
	fn add_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `3087`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3087)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: `ValidatorSet::ApprovedValidators` (r:1 w:1)
	/// Proof: `ValidatorSet::ApprovedValidators` (`max_values`: Some(1), `max_size`: Some(1602), added: 2097, mode: `MaxEncodedLen`)
	fn remove_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `3087`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3087)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

/// Unit weight implementation — zero cost, suitable for testing and parachains
/// that don't need fine-grained metering of these administrative calls.
impl WeightInfo for () {
	fn add_validator() -> Weight {
		Weight::zero()
	}
	fn remove_validator() -> Weight {
		Weight::zero()
	}
}
